### PR TITLE
add `--manifest` to warn if showing manifest status

### PR DESCRIPTION
**Pull request by IanButterworth**
Alt to #2990 

Fix https://github.com/JuliaLang/Pkg.jl/issues/2989

Closes #2990

cc. @fingolfin @DilumAluthge

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]
LGTM!

**Comment by KristofferC** [comment]
This doesn't make sense to me. Why would you then not show all packages (even those in the manifest) when you do `status`? The point about splitting up showing direct and indirect dependencies is that the direct dependencies are those you can directly change by changing the project file (e.g its compat). If all your packages are at the latest version but you still have some indirect dependency at the non latest version, that will not directly affect you since you are consuming the latest API of all your dependencies and indirect dependencies are more an implementation detail of your direct dependencies.

**Comment by DilumAluthge** [comment]
If I understand correctly, this isn't about `] status`, right? It's about `] update`.

I think that there are plenty of people that will assume that if they do `] update`, it will update all packages in their environment (both direct dependencies and indirect dependencies). So, if a user does `] update`, and then, after the update, one or more indirect dependencies are not at the latest version, then I absolutely think that we should print a warning to the user.

**Comment by KristofferC** [comment]
> then I absolutely think that we should print a warning to the user.

I don't think so because there is nothing as a user that you can do. If you are a power user / developer that wants to go and update the compat of your dependencies then you can just do `st --manifest` after. Showing warnings should be done very sparingly, people getting warnings when there is nothing they can really do is not user friendly in my opinion.

**Pull request closed without merging**
