### PR TITLE
prune manifest before instantiating

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
It's a bit weird to have a manifest in an unpruned state though... how did it happen in the first place?

**Comment by KristofferC** [comment]
People are doing strange things and get weird errors. 

https://discourse.julialang.org/t/travis-doesnt-tell-me-where-an-error-occurs/18160/4

and discussion in slack #pkg-usage today.

Perhaps just prune in the beginning of this function?

**Comment by fredrikekre** [comment]
Yea, lets prune directly

**Comment by KristofferC** [comment]
Alternatively, this should be caught in the manifest loader and immediately fail some verification check?

**Comment by 00vareladavid** [comment]
I'm working on more thorough checking for both the manifest and project files. Project checking is almost done, and I'll do manifest after that. In case that makes a difference...

**Comment by fredrikekre** [comment]
> fail some verification check?

This seems not very user friendly. How do you get out of such a problematic Manifest? Can't we just have a warning that some packages are orphaned and will not be instantiated?

**Comment by 00vareladavid** [comment]
perhaps have the option to run some recovery code? :thinking:

**Comment by 00vareladavid** [comment]
Agreed. Maybe we can just `@info` (or somehow log) in the validation phase that we detected some weird state and that we are recovering.

We could potentially lose data if we do recover automatically though. Should that be a issue?

**Comment by fredrikekre** [comment]
For this particular case it would just ignore some parts of the manifest, and not actually modify the files, but it would be nice to somehow let Pkg correct the files, such that you don't get the warning the next time you instantiate the same manifest.

**Comment by KristofferC** [comment]
`instantiate` does not write back the pruned data so no data loss there at least.

I think we should just not accept malformed input. Who knows what was intended and what a "recovery" should be.

**Comment by 00vareladavid** [comment]
That seems like the best option. Users should be using the API to create environments

**Comment by StefanKarpinski** [comment]
Triage conclusion: the job of `instantiate` is just to install all the things in the manifest and build them in a dependency compatible order; it should not try to sync up or even look at project file in any way.

**Comment by KristofferC** [comment]
Done

**Comment by StefanKarpinski** [comment]
I thought this was the opposite of what we decided but sure 🤷‍♂️

**Comment by KristofferC** [comment]
Ergh, I misremembered then :/. I don't think it will matter though.

**Comment by StefanKarpinski** [comment]
Yeah, this is fine.

**Pull request merged**
