### PR TITLE
fix package name in sandbox tests

### LINKED ISSUE #1565: Scary error message in CI log
```
Basic `test` sandboxing |    4      4
┌ Error: Error building `BasicSandbox`: 
│ ERROR: LoadError: ArgumentError: Package Foo not found in current path:
│ - Run `import Pkg; Pkg.add("Foo")` to install the Foo package.
│ 
│ Stacktrace:
│  [1] require(::Module, ::Symbol) at ./loading.jl:887
│  [2] include at ./boot.jl:328 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1105
│  [4] include(::Module, ::String) at ./Base.jl:31
│  [5] include(::String) at ./client.jl:424
│  [6] top-level scope at none:5
│ in expression starting at /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_RUh3Db/BasicSandbox/deps/build.jl:4
└ @ Pkg.Operations ~/build/JuliaLang/Pkg.jl/src/Operations.jl:883
```

In https://travis-ci.org/JuliaLang/Pkg.jl/jobs/629483592#L875-L888

Is this intended? Seems to be something with the sandboxing. cc @00vareladavid

### PR DESCRIPTION
**Pull request by 00vareladavid**
fix #1565

### CODE REVIEW

**Comment by KristofferC** [comment]
Is it expected that the tests passed even without this change?

**Comment by 00vareladavid** [comment]
No, it was a surprise to me that the error did not propagate. I'm not sure why yet. Probably best to take care of that as well in this PR

**Comment by 00vareladavid** [comment]
Ah I forget that `build` does not propagate errors

**Comment by 00vareladavid** [comment]
Wow, we even have an open issue for this: #1446

**Pull request merged**
