### PR TITLE
fix some invalidations with ChainRulesCore

### PR DESCRIPTION
**Pull request by simeonschaub**
Partner to JuliaLang/julia#39506

### CODE REVIEW

**Comment by simeonschaub** [comment]
Just realized this basically does the same as #2325. I don't really have a preference, either one seems fine.

**Comment by IanButterworth** [comment]
> Just realized this basically does the same as #2325.

Happy for your PRs to take over. I ran out of steam in my PRs on this

**Comment by IanButterworth** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/2325 has been merged, so I believe this isn't needed now?

**Comment by simeonschaub** [comment]
Yeah, awesome! Thanks!

**Pull request closed without merging**
