### PR TITLE
Don't clear executable bits in `set_readonly()` on Windows

### PR DESCRIPTION
**Pull request by staticfloat**
On windows, `filemode()` doesn't include executable bits.  This is already worked around in `gitmode()` but we don't quite want to do something as intrusive as `gitmode()` in `set_readonly()`; let's just work around this one platform-specific foible.

This fixes problems like executable permissions disappearing when creating artifacts on Windows, packages that contain executable files losing those permissions on install, etc...

### CODE REVIEW

**Comment by staticfloat** [comment]
For further discussion, see https://github.com/simeonschaub/ArtifactUtils.jl/pull/8#discussion_r767210865

**Comment by KristofferC** [comment]
Bump :)

**Comment by staticfloat** [comment]
*gulp* here we go

**Comment by staticfloat** [comment]
FTR I am not proposing we backport this to 1.9; I consider this a somewhat high-risk change, so let's let it settle on `master` a bit.

**Pull request merged**
