### PR TITLE
REPL should not throw on interrupt

### LINKED ISSUE #1421: ^C during password prompt should simply abort
Rather than throwing 100 lines of scary backtrace, just abort the operation and return me to the package prompt:
```
(ToyFHE) pkg> add https://github.com/Keno/FourierTransforms.jl#master
   Cloning git-repo `https://github.com/Keno/FourierTransforms.jl`
                                     ERROR: InterruptException:
Stacktrace:
 [1] poptaskref(::Base.InvasiveLinkedListSynchronized{Task}) at ./task.jl:660
 [2] wait() at ./task.jl:667
 [3] wait(::Base.GenericCondition{Base.Threads.SpinLock}) at ./condition.jl:106
 [4] #readuntil#525(::Bool, ::typeof(readuntil), ::Base.TTY, ::UInt8) at ./stream.jl:901
 [5] #readuntil at ./stream.jl:887 [inlined]
 [6] #readline#290(::Bool, ::typeof(readline), ::Base.TTY) at ./io.jl:454
 [7] #readline at ./io.jl:454 [inlined]
 [8] #prompt#714(::String, ::typeof(Base.prompt), ::Base.TTY, ::Base.TTY, ::String) at ./util.jl:564
 [9] (::Base.var"#kw##prompt")(::NamedTuple{(:default,),Tuple{String}}, ::typeof(Base.prompt), ::Base.TTY, ::Base.TTY, ::String) at ./util.jl:562
 [10] #prompt#715(::String, ::typeof(Base.prompt), ::String) at ./util.jl:572
 [11] #prompt at ./util.jl:572 [inlined]
 [12] authenticate_userpass(::Ptr{Ptr{Nothing}}, ::LibGit2.CredentialPayload) at /Users/kfischer/Projects/julia-doublecheck/usr/share/julia/stdlib/v1.4/LibGit2/src/callbacks.jl:214
 [13] credentials_callback(::Ptr{Ptr{Nothing}}, ::Cstring, ::Cstring, ::UInt32, ::LibGit2.CredentialPayload) at /Users/kfischer/Projects/julia-doublecheck/usr/share/julia/stdlib/v1.4/LibGit2/src/callbacks.jl:326
 [14] credentials_callback(::Ptr{Ptr{Nothing}}, ::Cstring, ::Cstring, ::UInt32, ::Dict{Symbol,Any}) at /Users/kfischer/Projects/julia-doublecheck/usr/share/julia/stdlib/v1.4/LibGit2/src/callbacks.jl:349
[snip]
```

### PR DESCRIPTION
**Pull request by 00vareladavid**
close #1421

### CODE REVIEW

**Comment by KristofferC** [comment]
I wonder if this is a bit too heavy-handed. A more "surgical" fix to the issue is to just do this around the place where the prompt appears. Not sure what is best.

**Comment by 00vareladavid** [comment]
I think this might be OK. Is there a case where it is useful to show a stacktrace when interrupting the REPL?

**Comment by KristofferC** [comment]
Maybe not. I guess sometimes when Pkg seems to get stuck, then Ctrl-C can give a backtrace which gives info to someone reporting a bug.

**Comment by 00vareladavid** [comment]
I see, that's a good point. lets go ahead with the more precise option then

**Comment by 00vareladavid** [comment]
I might revisit at some later point

**Pull request closed without merging**
