### PR TITLE
Documentation: Fix a typo in the "Tilde specifiers" section

### PR DESCRIPTION
**Pull request by DilumAluthge**
Currently, the "Tilde specifiers" section of the "Compatibility" documentation says the following:
```toml
PkgE = "~0.0.3" # [0.0.3, 0.0.4)
```

But this is not how tilde specifiers are currently implemented in Pkg. The correct documentation is:
```toml
PkgE = "~0.0.3" # [0.0.3, 0.1.0)
```

### CODE REVIEW

**Comment by DilumAluthge** [comment]
To illustrate, here is what I get on the latest Julia master:
```julia
julia> import Pkg

julia> v"0.0.3" in Pkg.Types.semver_spec("~0.0.3")
true

julia> v"0.0.4" in Pkg.Types.semver_spec("~0.0.3")
true

julia> v"0.0.5" in Pkg.Types.semver_spec("~0.0.3")
true

julia> v"0.0.6" in Pkg.Types.semver_spec("~0.0.3")
true

julia> v"0.1.0" in Pkg.Types.semver_spec("~0.0.3")
false

julia> v"0.0.3" in Pkg.Types.semver_spec("^0.0.3")
true

julia> v"0.0.4" in Pkg.Types.semver_spec("^0.0.3")
false

julia> v"0.0.5" in Pkg.Types.semver_spec("^0.0.3")
false

julia> v"0.0.6" in Pkg.Types.semver_spec("^0.0.3")
false

julia> v"0.1.0" in Pkg.Types.semver_spec("^0.0.3")
false

julia> v"0.0.3" in Pkg.Types.semver_spec("0.0.3")
true

julia> v"0.0.4" in Pkg.Types.semver_spec("0.0.3")
false

julia> v"0.0.5" in Pkg.Types.semver_spec("0.0.3")
false

julia> v"0.0.6" in Pkg.Types.semver_spec("0.0.3")
false

julia> v"0.1.0" in Pkg.Types.semver_spec("0.0.3")
false
```

**Comment by KristofferC** [comment]
Isn't this a bug and not a doc error?

**Comment by DilumAluthge** [comment]
> A tilde specifier provides more limited upgrade possibilities. When specifying major, minor and patch versions, or when specifying major and minor versions, only the patch version is allowed to change.

**Comment by DilumAluthge** [comment]
If my compat entry is `~0.0.3`, then I have specified major, minor, and patch. So per that description, only the patch should be allowed to change. Which means `0.0.4`, `0.0.5`, `0.0.6`, etc are allowed.

**Comment by KristofferC** [comment]
But

> A tilde specifier provides more limited upgrade possibilities

And `^0.0.3` is [0.0.3 - 0.0.3]` so to be more limited (or at leat equally limited) that is what tilde also has to do?

**Comment by DilumAluthge** [comment]
Ah, I see... yes it probably doesn’t make sense to have tilde be less limited than caret.

**Comment by DilumAluthge** [comment]
I’m closing this PR in favor of fixing the bug, as discussed above.

**Pull request closed without merging**
