### PR TITLE
remove telemetry; do not send client UUIDs

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Co-authored-by: Kristoffer Carlsson <kcarlsson89@gmail.com>

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
@KristofferC, should I change this to be against the `release-1.5` branch?

**Comment by KristofferC** [comment]
Yeah, that makes sense to me.

**Comment by fredrikekre** [comment]
Welp, thanks GitHub.

**Comment by StefanKarpinski** [comment]
😂 I'll rebase and repush.

**Comment by StefanKarpinski** [comment]
I'll do it later, got caught up in testing...

**Pull request merged**
