### PR TITLE
Transfer can_inline to subprocess

### PR DESCRIPTION
**Pull request by fingolfin**
This is meant as an alternative to PR #866 for resolving issue #865

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
@KristofferC is going to reword the doc a bit and then we'll merge this.

**Comment by diegozea** [comment]
@tkelman @ninjin @staticfloat @simonbyrne Should the default Travis CI script for Julia use this `inline=no` when `codecov` or `coveralls` is set to `true` ? I'm using the default scripts and I'm seeing the coverage drop reported in https://github.com/JuliaCI/Coverage.jl/issues/187

**Comment by KristofferC** [comment]
Only if we make `coverage=false` the default because `inline=no` is typically too slow to be usable in my experience.

**Comment by StefanKarpinski** [comment]
Please don't ping so many people—everyone who watches this repo will already get this.

**Comment by diegozea** [comment]
I'm sorry. I've just used the list suggested by [Travis CI docs](https://docs.travis-ci.com/user/languages/julia/) without checking the list of watchers.

**Comment by StefanKarpinski** [comment]
Hah, ok, you did follow the instructions exactly. Those instructions should be updated!

**Pull request merged**
