### PR TITLE
Document the interpretation of compat ranges in registries

### PR DESCRIPTION
**Pull request by timholy**
This is a start on #1190. @StefanKarpinski or others, feel free to modify at will.

### CODE REVIEW

**Comment by KristofferC** [comment]
This might get obsoleted by https://github.com/JuliaLang/Pkg.jl/pull/1410 where we also have the same hyphen compat specifier as the registry uses.

**Comment by nickrobinson251** [comment]
Bump?

**Comment by timholy** [comment]
Presumably this can be closed due to https://julialang.github.io/Pkg.jl/dev/compatibility/#Hyphen-specifiers-1, right?

**Comment by nickrobinson251** [comment]
Do hyphen ranges in Project.toml ahve exact same semantics as in a registry's Compat.toml?
E.g.
```toml
"0.7-0.8"  # [0.7.0, 0.9.0)
"0.7-0"    # [0.7.0, 1.0.0)
"0.8.6-0"  # [0.8.6, 1.0.0)
"0.7-*"    # [0.7.0, ∞)
```

**Pull request merged**
