### PR TITLE
give packages without project uuids based on their name instead of a random uuid

### PR DESCRIPTION
**Pull request by KristofferC**
Should fix https://github.com/JuliaLang/Pkg.jl/pull/402#issuecomment-398176050 point 9.

Would be good with a test but I don't want to spend too much time adding test for things that are just for compatibility with REQUIRE.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Won't this lead to different people all getting the same UUID if they happen to pick the same name, which is not ok at all.

**Comment by KristofferC** [comment]
> different people all getting the same UUID if they happen to pick the same name

Should be pointed out that this is not when creating new packages with `generate`. This is uppon adding (from a repo) or devving a package that neither have a Project file, nor is registered. This is purely a convenience thing while things are moving to Projects to allow people to incrementally add Projects to their packages. Before, the following situation would arise:

Local package A with project file:
 `dev local/Q ->  uuid_Q_1`
(we have package Q uuid `uuid_Q_1`).

Project B:
`dev local/Q -> uuid_Q_2`
(this time Q got uuid `uuid_Q_2`).

Project B:
`dev A`
 
So `A` depends on `Q` with `uuid_Q_1` but the one we have in our current manifest is `uuid_Q_2`.
Package `A` will thus fail to load from project `B`. This is because we gave a different UUID to the same package `Q`.
If we have no uuid (no project file, no registry) we assume that they are the same package (which is what the old Pkg does, and that is what is emulated here until things get project files).

**Comment by StefanKarpinski** [comment]
What about generating a UUID based on the Mac address and realpath to the package then?

**Comment by raminammour** [comment]
What about just doing supporting `generate` would have done for old existing local package (no `*.toml`, non git). And just issuing an error upon:
```
dev local/Q
Error: run this command on `local/Q` to generate uuid... and run dev local/Q again
```
I for one would want to fix all my old existing local packages once and for all :)

If there is a way to do this already without renaming folder/creating folder with same name/ copying, I would love to hear about it...

**Comment by KristofferC** [comment]
The PR that adds this functionality is https://github.com/JuliaLang/Pkg.jl/pull/392 but there is still some stuff left with the version bounds on dependencies to work out how to convert in the best way.

**Comment by KristofferC** [comment]
The previous package manager identified packages by name so that is what we have to do as well to use old packages smoothly. Again, this is just a convenience thing so people don't get inexplicable uuid inconcistencies when using their old packages. I really don't think this will cause any problems and if it does we can revisit.

**Comment by StefanKarpinski** [comment]
Ok, carry on then.

**Pull request merged**
