### PR TITLE
pkg client: add a session header

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by KristofferC** [comment]
What is this used for? Are there any docs for the package server / protocol for it?

**Comment by StefanKarpinski** [comment]
Not used for anything. It would allow server-side log analysis to tell which requests are from the same Julia client session without being able to tie it back to the client in any way since this ID is never stored anywhere.

**Comment by KristofferC** [comment]
So what would it be used for?

**Comment by StefanKarpinski** [comment]
> It would allow server-side log analysis to tell which requests are from the same Julia client session without being able to tie it back to the client in any way since this ID is never stored anywhere.

**Pull request closed without merging**
