### PR TITLE
Add an example for the SSH-based git protocol.

### LINKED ISSUE #321: add doesn't support SSH clones
```julia
(pkgtest) pkg> add git@github.com:jrevels/Cassette.jl.git
ERROR: ArgumentError: invalid version range: "github.com:jrevels/Cassette.jl.git"
Stacktrace:
 [1] Pkg.Types.VersionRange(::SubString{String}) at /Users/twan/code/julia/julia/usr/share/julia/stdlib/v0.7/Pkg/src/Types.jl:161
 [2] tokenize!(::Array{SubString{String},1}) at /Users/twan/code/julia/julia/usr/share/julia/stdlib/v0.7/Pkg/src/REPLMode.jl:214
 [3] tokenize(::String) at /Users/twan/code/julia/julia/usr/share/julia/stdlib/v0.7/Pkg/src/REPLMode.jl:177
 [4] #do_cmd#8(::Bool, ::Function, ::REPL.LineEditREPL, ::String) at /Users/twan/code/julia/julia/usr/share/julia/stdlib/v0.7/Pkg/src/REPLMode.jl:231
 [5] do_cmd at /Users/twan/code/julia/julia/usr/share/julia/stdlib/v0.7/Pkg/src/REPLMode.jl:230 [inlined]
 [6] (::getfield(Pkg.REPLMode, Symbol("##27#30")){REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /Users/twan/code/julia/julia/usr/share/julia/stdlib/v0.7/Pkg/src/REPLMode.jl:948
 [7] top-level scope
```

I guess part of the problem is that the `@` conflicts with the `Pkg` version syntax.

### PR DESCRIPTION
**Pull request by tpapp**
Fixes #321.

### CODE REVIEW

**Comment by fredrikekre** [comment]
You can also just quote it, right?
```
pkg> add "git@github.com:JuliaLang/Pkg.jl.git"
```
should work.

**Comment by tpapp** [comment]
Yes, that works too. I will update the PR.

**Comment by felipenoris** [comment]
@tpapp I would like to suggest to add a note telling about:

(1) how to handle branches
```
pkg> add "git@gitlab.mycompany.net:group/MyPkg.jl.git"#branch
```

(2) how to use this from a script:

```
using Pkg
pkg"add \"git@gitlab.mycompany.net:group/MyPkg.jl.git\"#branch"
```

Ref #2075.

**Comment by tpapp** [comment]
From a script, I would use the package API. See the first commit in this PR.

**Pull request merged**
