### PR TITLE
add ability to pin / free all deps in manifest

### PR DESCRIPTION
**Pull request by IanButterworth**
The idea came up [on discourse](https://discourse.julialang.org/t/first-pluto-notebook-launches-are-slower-on-julia-1-9-beta-3/93429/53) to be able to pin/free all the indirect deps too, for distribution of a locked down manifest that is harder to upgrade, for classes etc.

```
(jl_MRLBHQ) pkg> st
Status `/tmp/jl_MRLBHQ/Project.toml`
  [336ed68f] CSV v0.10.9

(jl_MRLBHQ) pkg> pin --all
   Resolving package versions...
    Updating `/tmp/jl_MRLBHQ/Project.toml`
  [336ed68f] ~ CSV v0.10.9 ⇒ v0.10.9 ⚲
    Updating `/tmp/jl_MRLBHQ/Manifest.toml`
  [336ed68f] ~ CSV v0.10.9 ⇒ v0.10.9 ⚲

(jl_MRLBHQ) pkg> pin --all -m
   Resolving package versions...
  No Changes to `/tmp/jl_MRLBHQ/Project.toml`
    Updating `/tmp/jl_MRLBHQ/Manifest.toml`
  [944b1d66] ~ CodecZlib v0.7.1 ⇒ v0.7.1 ⚲
  [34da2185] ~ Compat v4.5.0 ⇒ v4.5.0 ⚲
  [9a962f9c] ~ DataAPI v1.14.0 ⇒ v1.14.0 ⚲
  [e2d170a0] ~ DataValueInterfaces v1.0.0 ⇒ v1.0.0 ⚲
  [48062228] ~ FilePathsBase v0.9.20 ⇒ v0.9.20 ⚲
  [842dd82b] ~ InlineStrings v1.3.2 ⇒ v1.3.2 ⚲
  [82899510] ~ IteratorInterfaceExtensions v1.0.0 ⇒ v1.0.0 ⚲
  [bac558e1] ~ OrderedCollections v1.4.1 ⇒ v1.4.1 ⚲
  [69de0a69] ~ Parsers v2.5.3 ⇒ v2.5.3 ⚲
  [2dfb63ee] ~ PooledArrays v1.4.2 ⇒ v1.4.2 ⚲
  [21216c6a] ~ Preferences v1.3.0 ⇒ v1.3.0 ⚲
  [91c51154] ~ SentinelArrays v1.3.17 ⇒ v1.3.17 ⚲
  [66db9d55] ~ SnoopPrecompile v1.0.3 ⇒ v1.0.3 ⚲
  [3783bdb8] ~ TableTraits v1.0.1 ⇒ v1.0.1 ⚲
  [bd369af6] ~ Tables v1.10.0 ⇒ v1.10.0 ⚲
  [3bb67fe8] ~ TranscodingStreams v0.9.11 ⇒ v0.9.11 ⚲
  [ea10d353] ~ WeakRefStrings v1.4.2 ⇒ v1.4.2 ⚲
  [76eceee3] ~ WorkerUtilities v1.6.1 ⇒ v1.6.1 ⚲
  [56f22d72] ~ Artifacts ⇒ ⚲
  [2a0f44e3] ~ Base64 ⇒ ⚲
  [ade2ca70] ~ Dates ⇒ ⚲
  [9fa8497b] ~ Future ⇒ ⚲
  [b77e0a4c] ~ InteractiveUtils ⇒ ⚲
  [8f399da3] ~ Libdl ⇒ ⚲
  [37e2e46d] ~ LinearAlgebra ⇒ ⚲
  [56ddb016] ~ Logging ⇒ ⚲
  [d6f4376e] ~ Markdown ⇒ ⚲
  [a63ad114] ~ Mmap ⇒ ⚲
  [de0858da] ~ Printf ⇒ ⚲
  [9a3f8284] ~ Random ⇒ ⚲
  [ea8e919c] ~ SHA v0.7.0 ⇒ v0.7.0 ⚲
  [9e88b42a] ~ Serialization ⇒ ⚲
  [fa267f1f] ~ TOML v1.0.3 ⇒ v1.0.3 ⚲
  [8dfed614] ~ Test ⇒ ⚲
  [cf7118a7] ~ UUIDs ⇒ ⚲
  [4ec0a83e] ~ Unicode ⇒ ⚲
  [e66e0078] ~ CompilerSupportLibraries_jll v1.0.2+0 ⇒ v1.0.2+0 ⚲
  [4536629a] ~ OpenBLAS_jll v0.3.21+0 ⇒ v0.3.21+0 ⚲
  [83775a58] ~ Zlib_jll v1.2.13+0 ⇒ v1.2.13+0 ⚲
  [8e850b90] ~ libblastrampoline_jll v5.2.0+0 ⇒ v5.2.0+0 ⚲

(jl_MRLBHQ) pkg> free --all -m
   Resolving package versions...
    Updating `/tmp/jl_MRLBHQ/Project.toml`
  [336ed68f] ~ CSV v0.10.9 ⚲ ⇒ v0.10.9
    Updating `/tmp/jl_MRLBHQ/Manifest.toml`
  [336ed68f] ~ CSV v0.10.9 ⚲ ⇒ v0.10.9
  [944b1d66] ~ CodecZlib v0.7.1 ⚲ ⇒ v0.7.1
  [34da2185] ~ Compat v4.5.0 ⚲ ⇒ v4.5.0
  [9a962f9c] ~ DataAPI v1.14.0 ⚲ ⇒ v1.14.0
  [e2d170a0] ~ DataValueInterfaces v1.0.0 ⚲ ⇒ v1.0.0
  [48062228] ~ FilePathsBase v0.9.20 ⚲ ⇒ v0.9.20
  [842dd82b] ~ InlineStrings v1.3.2 ⚲ ⇒ v1.3.2
  [82899510] ~ IteratorInterfaceExtensions v1.0.0 ⚲ ⇒ v1.0.0
  [bac558e1] ~ OrderedCollections v1.4.1 ⚲ ⇒ v1.4.1
  [69de0a69] ~ Parsers v2.5.3 ⚲ ⇒ v2.5.3
  [2dfb63ee] ~ PooledArrays v1.4.2 ⚲ ⇒ v1.4.2
  [21216c6a] ~ Preferences v1.3.0 ⚲ ⇒ v1.3.0
  [91c51154] ~ SentinelArrays v1.3.17 ⚲ ⇒ v1.3.17
  [66db9d55] ~ SnoopPrecompile v1.0.3 ⚲ ⇒ v1.0.3
  [3783bdb8] ~ TableTraits v1.0.1 ⚲ ⇒ v1.0.1
  [bd369af6] ~ Tables v1.10.0 ⚲ ⇒ v1.10.0
  [3bb67fe8] ~ TranscodingStreams v0.9.11 ⚲ ⇒ v0.9.11
  [ea10d353] ~ WeakRefStrings v1.4.2 ⚲ ⇒ v1.4.2
  [76eceee3] ~ WorkerUtilities v1.6.1 ⚲ ⇒ v1.6.1
  [56f22d72] ~ Artifacts ⚲ ⇒ 
  [2a0f44e3] ~ Base64 ⚲ ⇒ 
  [ade2ca70] ~ Dates ⚲ ⇒ 
  [9fa8497b] ~ Future ⚲ ⇒ 
  [b77e0a4c] ~ InteractiveUtils ⚲ ⇒ 
  [8f399da3] ~ Libdl ⚲ ⇒ 
  [37e2e46d] ~ LinearAlgebra ⚲ ⇒ 
  [56ddb016] ~ Logging ⚲ ⇒ 
  [d6f4376e] ~ Markdown ⚲ ⇒ 
  [a63ad114] ~ Mmap ⚲ ⇒ 
  [de0858da] ~ Printf ⚲ ⇒ 
  [9a3f8284] ~ Random ⚲ ⇒ 
  [ea8e919c] ~ SHA v0.7.0 ⚲ ⇒ v0.7.0
  [9e88b42a] ~ Serialization ⚲ ⇒ 
  [fa267f1f] ~ TOML v1.0.3 ⚲ ⇒ v1.0.3
  [8dfed614] ~ Test ⚲ ⇒ 
  [cf7118a7] ~ UUIDs ⚲ ⇒ 
  [4ec0a83e] ~ Unicode ⚲ ⇒ 
  [e66e0078] ~ CompilerSupportLibraries_jll v1.0.2+0 ⚲ ⇒ v1.0.2+0
  [4536629a] ~ OpenBLAS_jll v0.3.21+0 ⚲ ⇒ v0.3.21+0
  [83775a58] ~ Zlib_jll v1.2.13+0 ⚲ ⇒ v1.2.13+0
  [8e850b90] ~ libblastrampoline_jll v5.2.0+0 ⚲ ⇒ v5.2.0+0
```

### CODE REVIEW

**Comment by Seelengrab** [comment]
I actually thought `]pin --all` would pin indirect dependencies already, since "freezing the current manifest" seems like that's what it's supposed to do :D

**Comment by PallHaraldsson** [comment]
Shouldn't `pin --all` just pin indirect dependencies too? That's what "all" would imply to me, and if old behavior is sometimes needed then rather add `pin --all --exclude-indirect` if the "breaking change" is an issue. I doubt we promise for this, and need to keep strict compatibility (or even add that option).

**Comment by IanButterworth** [comment]
Yeah, it does seem to make more sense that `--all` alone does this. Proposed here https://github.com/JuliaLang/Pkg.jl/pull/3346

**Comment by IanButterworth** [comment]
@Seelengrab 
> Should there be some special message to print when a user does ]up when all dependencies are pinned and there's no work to do?

Good idea. Added to #3346

**Comment by IanButterworth** [comment]
Closing in favor of #3346

**Pull request closed without merging**
