### PR TITLE
Flush stdin before showing package install prompt

### LINKED ISSUE #3054: Prompt to install package should purge input buffer before reading from it
This just happened to me.  Note the newlines and the following REPL prompts (that immediately appeared after installing):

```
julia> using Foo


 │ Package Foo not found, but a package named Foo is available from a registry. 
 │ Install package?
 │   (@v1.7) pkg> add Foo 
 └ (y/n) [y]: n


    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed Foo ─ v0.3.2
    Updating `~/.julia/environments/v1.7/Project.toml`
  [a1216acd] + Foo v0.3.2
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [a1216acd] + Foo v0.3.2
  [4722fa14] + Bar v1.1.1
  [d3707c4a] + Baz_jll v1.55.1+0
Precompiling project...
  1 dependency successfully precompiled in 6 seconds (33 already precompiled)

julia> 

julia> n
ERROR: UndefVarError: n not defined
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes #3054

### CODE REVIEW

**Comment by IanButterworth** [comment]
Actually, the flush doesn't seem to be enough. I'm throwing a bunch of newlines in here while the prompt compiles, and they're not being ignored
```
julia> using Flux



 │ Package Flux not found, but a package named Flux is available from a registry. 
 │ Install package?
 │   (jl_fvEGFB) pkg> add Flux 
 └ (y/n/o) [y]: n
    Updating registry at `~/.julia/registries/General.toml`
...
```

**Comment by IanButterworth** [comment]
@vtjnash any idea why a flush doesn't work here? I'm trying to ignore any keypresses from before the prompt shows

**Comment by vtjnash** [comment]
What do you think flush does?

**Comment by IanButterworth** [comment]
Empty any buffered data?

If that's not the case (which I'm inferring from your response) then I assume this needs a `read` instead?

**Comment by IanButterworth** [comment]
This doesn't work locally.

Without any keypresses it hangs until a return keypress here, so I assume `readavailable` is waiting (which seems odd)
```
julia> using Flux
 │ Package Flux not found, but a package named Flux is available from a registry. 
 │ Install package?
 │   (@v1.9) pkg> add Flux 
 └ 
```

and with returns pressed before the prompt it interprets the returns as a confirm:
```
julia> using Flux


 │ Package Flux not found, but a package named Flux is available from a registry. 
 │ Install package?
 │   (@v1.9) pkg> add Flux 
 └ (y/n/o) [y]: n
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
...
```

If what should be done is clear to you @vtjnash I'd appreciate that being pointed out. Thanks

**Comment by vtjnash** [comment]
Ah, you want TCIFLUSH instead of this, which does a tty drain (awkwardly, tty got the names swapped from everyone else 🤦)

**Comment by IanButterworth** [comment]
Ah ok. Am I right in saying that's not implemented in Base?

I did find this though https://github.com/kdheepak/TERMIOS.jl/blob/c7e23eb42cf9edf0b2b053a79956e38a741cd2c0/src/TERMIOS.jl#L670

**Comment by IanButterworth** [comment]
Closing to tidy up given there is an issue to track

**Pull request closed without merging**
