### PR TITLE
Introduce env navigation syntax

### PR DESCRIPTION
**Pull request by 00vareladavid**
Changes:
- introduce `activate` sandbox support e.g. `activate +test`
- introduce `activate` "backjump" support e.g. `activate -`
- introduce `activate` shared env "@" syntax e.g. `activate @foo`

### CODE REVIEW

**Comment by 00vareladavid** [comment]
bors try

**Comment by 00vareladavid** [comment]
bors try

**Comment by 00vareladavid** [comment]
bors try

**Comment by 00vareladavid** [comment]
Feedback on syntax additions? Otherwise I feel this is good to go

**Comment by fredrikekre** [comment]
Could we perhaps discuss this a bit more? I am not a fan :stuck_out_tongue: 
bors r-

**Comment by 00vareladavid** [comment]
Ok, that's understandable

**Comment by oxinabox** [comment]
I wanted to pop up the stack of enviroments.

I am defining 5 subenviroments, with a single common shared enviroment.
And just for purposes of setting them all up 
i would be doing 
```
activate common
activate Special1
add Special1Pkg
activate - 
activate Special2
add Special2Pkg
activate - 
...
```

But since there is no way to just pop the tiop enviroment
I am currently just going to quit between each.

**Comment by StefanKarpinski** [comment]
I have encountered something similar. When I activate the `test` "sub environment" for a project, I want to keep the main environment for the project in the load path as well. I'm not sure what the best mechanism for it is, but currently I've had to just push it into the load path manually, which is awkward.

**Comment by 00vareladavid** [comment]
More evidence that people tend to think in terms of the active environment is: #1215. Instead of having to `cd` then `dev`, it would be nicer if users could just e.g. `pkg> dev +relative/path`.

**Comment by 00vareladavid** [comment]
I have come around to agreeing with @fredrikekre on this. If anything, a more appropriate place for this is in an extension package

**Comment by StefanKarpinski** [comment]
Could we please have the `activate @foo` syntax part though?

**Comment by KristofferC** [comment]
That's a shorthand for `activate --shared foo`?

**Comment by StefanKarpinski** [comment]
Yes, that was the idea. It would also be a more general syntax: `@foo` anywhere in a command would refer to the named environment `foo`.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/1488

**Comment by StefanKarpinski** [comment]
Great. I thought that was around somewhere.

**Pull request closed without merging**
