### PR TITLE
Use max/min instead of a list to specify argument count

### LINKED ISSUE #586: REPL Mode: add or develop should probably error if no args are given
```
(v0.7) pkg> add
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
```

### PR DESCRIPTION
**Pull request by 00vareladavid**
Should resolve #586. Should be merged after #595 (to avoid merge conflicts).

### CODE REVIEW

**Comment by 00vareladavid** [comment]
bors try

**Comment by 00vareladavid** [comment]
bors try

**Comment by 00vareladavid** [comment]
bors try

**Comment by 00vareladavid** [comment]
@KristofferC this one is good to go. It should also help with more clear error messages in #662.

**Comment by KristofferC** [comment]
Please squash before merging

bors delegate+

**Pull request merged**
