### PR TITLE
More informative error messages when parsing manifest files.

### LINKED ISSUE #1318: "Dependency name does not match UUID" error could be better
```
(FHE) pkg> st
ERROR: Dependency name does not match UUID
```
I think the problem may be that I renamed the package, but this error message wasn't particularly helpful and coupe be improved (ideally with instruction on how to get out of this mess ;) ).

### PR DESCRIPTION
**Pull request by 00vareladavid**
This enhances error messages from the manifest parsing logic.

---
Fix #1318 
The error from #1318 will now read:
```
ERROR: `DocStringExtensions=ffbed154-4ef7-542d-bbb7-c09d3a79fcae` depends on `Pkg=748391e3-3ea3-41aa-8037-d96b5d03e7c6`, but entry with UUID `748391e3-3ea3-41aa-8037-d96b5d03e7c6` has name `Pkg2`.
```

### CODE REVIEW

**Comment by KristofferC** [comment]
Looks like an improvement. If we don't want to write the UUIDs so verbosely we could write it something like `DocstringExtensions [ffbed154]` which is a bit similar to how we do it in Pkg.status(). But doesn't matter that much since this error should be quite rare, so LGTM.

**Comment by 00vareladavid** [comment]
Yeah that error should only happen when someone manually edits their manifest

bors r+

**Pull request merged**
