### PR TITLE
try use Windows on Travis and drop AV

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
bors try

**Comment by KristofferC** [comment]
ok.. windows servers on Travis hit 50 min max time and terminated... Linux runs in 9 min. Wat.

**Comment by KristofferC** [comment]
bors try

**Comment by KristofferC** [comment]
bors try

**Comment by KristofferC** [comment]
bors try

**Comment by KristofferC** [comment]
bors try-

**Comment by KristofferC** [comment]
bors try

**Comment by KristofferC** [comment]
Whyyyy is only AV running Bors??

**Comment by fredrikekre** [comment]
Broken `.travis.yml` I guess?

**Comment by KristofferC** [comment]
Maybe, but I shoved it through YAML verifier and it was ok and it ran before and I don't think I changed anything.

**Comment by fredrikekre** [comment]
`Build config did not create any jobs`:

https://travis-ci.org/JuliaLang/Pkg.jl/requests

**Comment by 00vareladavid** [comment]
I'm closing as this does not seem to be necessary anymore. I apologize in advance if that is not the case!

**Pull request closed without merging**
