### PR TITLE
Silence 7z output

### PR DESCRIPTION
**Pull request by musm**
Silence 7z output

### CODE REVIEW

**Comment by musm** [comment]
Fix https://github.com/JuliaLang/Pkg.jl/issues/1376

note 7zip is annoying in that 7zip does not have silent mode.

**Comment by musm** [comment]
cc @staticfloat, same change as in BinaryProvider

**Comment by fredrikekre** [comment]
Looks like this is included in #1405

**Comment by musm** [comment]
Ok, I did open this PR first.

**Pull request closed without merging**
