### PR TITLE
Remove `mode` field from `PackageSpec`

### PR DESCRIPTION
**Pull request by 00vareladavid**
It seems that the main use for this was to decide whether to use `manifest_resolve!` or `package_deps_resolve!`. I don't think it makes much sense to have the packages carry this around everywhere and have the calling function set the mode for each package. 

A new function, `pkg_resolve!`, handles this now.

### CODE REVIEW

**Comment by KristofferC** [comment]
You need to update the doc strings for all the methods. Also, there is nothing now preventing you from mixing modes in the package list but this would prevent that.

**Comment by 00vareladavid** [comment]
I tried grepping through the code and it seems `PackageSpec` is the only affected docstring. But I definitely could have missed some!

**Comment by KristofferC** [comment]
Since this has been documented now it would be breaking to remove so I think we can keep it as is for now.

**Comment by 00vareladavid** [comment]
ok, that's a fair point

**Pull request closed without merging**
