### PR TITLE
use Base.download to get archives

### PR DESCRIPTION
**Pull request by simonbyrne**
Note: I haven't actually tested this (see #279).

### CODE REVIEW

**Comment by KristofferC** [comment]
What the reason for BinaryProvider not using `Base.download` @staticfloat

**Comment by KristofferC** [comment]
This now prints

```
 Resolving package versions...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   128    0   128    0     0   1809      0 --:--:-- --:--:-- --:--:--  1828
  0     0    0  2132    0     0  17149      0 --:--:-- --:--:-- --:--:-- 2082k
```

and we spawn multiple downloads at once so it will look pretty bad I think.

**Comment by staticfloat** [comment]
Back in the day, it was because the powershell implementation was broken, and we couldn't update people's `Base` as easily as we could update `BinaryProvider`. Only three reasons nowadays:

(1) More flexible output handling

(2) Resume capabilities (e.g. for large downloads on flaky connections)

(3) Doesn't require the usage of the `which` utility.  (This will be fixed by https://github.com/JuliaLang/julia/pull/26559)

**Comment by KristofferC** [comment]
Well, the docs of `download` says

> For production use or situations in which more options are needed, please use a package that provides the desired functionality instead.

I wanted to easily redirect the output, so that's what I did.

**Comment by simonbyrne** [comment]
We should probably add a "suppress output" option to Base.download then.

**Comment by staticfloat** [comment]
In `Pkg3`, I tend to agree, but `BinaryProvider` has pretty specific requirements in that we want to use the `OutputCollector` functionality which does things like logs to files, interleaves `stdout` and `stderr` on a per-line basis, colorizes output, etc..... We want all of that, and so we can't just use a `download()` function, we need something that provides a `Cmd` that we can then pass to `OutputCollector`, because the only way to get the `stdout` and `stderr` streams directly is to call `spawn()` directly.  So I don't think `BinaryProvider` will be able to use `Base.download()`.

**Comment by simonbyrne** [comment]
I don't see how that changes my argument

**Comment by staticfloat** [comment]
> I don't see how that changes my argument

If by that you mean "this change should still be merged regardless of what `BinaryProvider` does" then yes, I agree and that's what I was trying to communicate.

If by that you mean "My point still stands about only having one `download()` function, and all implementations should use the one implementation in `Base`, I believe my point above is addressing that pretty well; I don't want a `download()` function, I want a `gen_download_cmd()` function, and that doesn't seem like something that would be exported from `Base`, so we resort to writing our own.

**Comment by simonbyrne** [comment]
My understanding (which might be wrong) is that BinaryProvider.jl is intended to become part of the stdlib, in which case we will end up with 2 "download" implementations in the standard Julia distribution.

I don't see why your requests (which are entirely reasonable) can't be accommodated in the standard Julia `download` function, wherever it might live.

That said, this might better be discussed as an issue in the julia repo itself.

**Comment by simonbyrne** [comment]
re: silent download, there is an old PR https://github.com/JuliaLang/julia/pull/15930

**Comment by KristofferC** [comment]
`Base.download` doesn't provide the flexibility we need right now. We can revisit when it does.

**Pull request closed without merging**
