### PR TITLE
Stop printing "restricted by" if all versions are allowed.

### PR DESCRIPTION
**Pull request by Dsantra92**
Fixes https://github.com/JuliaLang/Pkg.jl/issues/2012

### CODE REVIEW

**Comment by KristofferC** [comment]
Do you have some example resolver backtraces from before and after?

**Comment by Dsantra92** [comment]
No I haven't found any suitable set of tests to check this fix. I asked for an example  to test my fix in the issue thread linked with this pr few days back [(here)](https://github.com/JuliaLang/Pkg.jl/issues/2012#issuecomment-734984189), sadly there was no response, so I rechecked my logic and made the pr. If you have some tests in mind I am ready to run it.

**Comment by yha** [comment]
If this is still waiting for an example, here is one:
```
[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
RLEVectors = "17b45ede-fd0d-54ef-b825-8cf9fc64da95"
ScanDir = "af3a3400-1793-11ea-1d1f-a522511abb08"


[compat]
RLEVectors = "0.9"
```

In this environment, doing `]add JLD2@0.4.11`,
```
(jl_AtWe3p) pkg> add JLD2@0.4.11
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Reexport [189a3867]:
 Reexport [189a3867] log:
 ├─possible versions are: 0.2.0-1.1.0 or uninstalled
 ├─restricted by compatibility requirements with Blink [ad839575] to versions: 0.2.0-1.1.0
 │ └─Blink [ad839575] log:
 │   ├─possible versions are: 0.8.0-0.12.5 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 0.8.0-0.12.5
 ├─restricted by compatibility requirements with RLEVectors [17b45ede] to versions: 0.2.0
 │ └─RLEVectors [17b45ede] log:
 │   ├─possible versions are: 0.7.0-0.9.6 or uninstalled
 │   └─restricted to versions 0.9 by an explicit requirement, leaving only versions 0.9.0-0.9.6
 └─restricted by compatibility requirements with JLD2 [033835bb] to versions: 1.0.0-1.1.0 — no versions left
   └─JLD2 [033835bb] log:
     ├─possible versions are: 0.1.0-0.4.11 or uninstalled
     └─restricted to versions 0.4.11 by an explicit requirement, leaving only versions 0.4.11
```
The whole `Blink` branch here is redundant.

**Comment by Dsantra92** [comment]
@yha I will check it out soon.

**Comment by Dsantra92** [comment]
@yha I believe the example is now outdated. Pkg downgrades JLD it smoothly with/without this patch.
```julia
  (temp) pkg> add JLD2@0.4.11
   Resolving package versions...
    Updating `~/junl/Project.toml`
  [033835bb] ↓ JLD2 v0.4.13 ⇒ v0.4.11
    Updating `~/junl/Manifest.toml`
  [033835bb] ↓ JLD2 v0.4.13 ⇒ v0.4.11
``` 
You example was working few weeks back when I first tried, do you any  method  to reproduce that again?

**Comment by Dsantra92** [comment]
Previous resolve log:
```julia
 Resolving package versions...
ERROR: LoadError: Unsatisfiable requirements detected for package Reexport [189a3867]:
 Reexport [189a3867] log:
 ├─possible versions are: 0.2.0-1.1.0 or uninstalled
 ├─restricted by compatibility requirements with Blink [ad839575] to versions: 0.2.0-1.1.0
 │ └─Blink [ad839575] log:
 │   ├─possible versions are: 0.8.0-0.12.5 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 0.8.0-0.12.5
 ├─restricted by compatibility requirements with RLEVectors [17b45ede] to versions: 0.2.0
 │ └─RLEVectors [17b45ede] log:
 │   ├─possible versions are: 0.7.0-0.9.7 or uninstalled
 │   └─restricted to versions 0.9.6 by an explicit requirement, leaving only versions 0.9.6
 └─restricted by compatibility requirements with JLD2 [033835bb] to versions: 1.0.0-1.1.0 — no versions left
   └─JLD2 [033835bb] log:
     ├─possible versions are: 0.1.0-0.4.13 or uninstalled
     └─restricted to versions 0.4.11 by an explicit requirement, leaving only versions 0.4.11
```

Current resolve log:

```julia
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
ERROR: LoadError: Unsatisfiable requirements detected for package Reexport [189a3867]:
 Reexport [189a3867] log:
 ├─possible versions are: 0.2.0-1.1.0 or uninstalled
 ├─restricted by compatibility requirements with RLEVectors [17b45ede] to versions: 0.2.0
 │ └─RLEVectors [17b45ede] log:
 │   ├─possible versions are: 0.7.0-0.9.7 or uninstalled
 │   └─restricted to versions 0.9.6 by an explicit requirement, leaving only versions 0.9.6
 └─restricted by compatibility requirements with JLD2 [033835bb] to versions: 1.0.0-1.1.0 — no versions left
   └─JLD2 [033835bb] log:
     ├─possible versions are: 0.1.0-0.4.13 or uninstalled
     └─restricted to versions 0.4.11 by an explicit requirement, leaving only versions 0.4.11
```

**Comment by KristofferC** [comment]
Thanks! @carlobaldassi, does this look ok to you?

**Comment by IanButterworth** [comment]
This seems good to go. I'll merge when tests pass

**Comment by IanButterworth** [comment]
Just hit this on master (with this PR) where the only restriction is julia version compat
```
(@v1.8) pkg> add TestEnv
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package TestEnv [1e6cf692]:
 TestEnv [1e6cf692] log:
 ├─possible versions are: 1.0.0-1.7.2 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 1.0.0-1.7.2
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by carlobaldassi** [comment]
> The whole Blink branch here is redundant.

But it's not *entirely* redundant, right? It serves to remove the "uninstalled" option (and then shows that Blink was required and depends on Reexport).

**Comment by yha** [comment]
But `Reexport` is required anyway by `RLEVectors` and `JLD2`, which are causing the conflict. The presence of `Blink` makes no difference, does it?
And in the `TestEnv` example above, a branch which only removed "uninstalled" is correctly still displayed when it does participate in the conflict.

**Comment by carlobaldassi** [comment]
But in the `TestEnv` example above, the second line (the one that removes the "uninstalled" option) comes from another piece of code, that deals with explicit requiremend ([this one](https://github.com/JuliaLang/Pkg.jl/blob/092999b63d36850beef747dd18e0260d4e2cac41/src/Resolve/graphtype.jl#L650-L682)).

With the change in this PR, there is no mechanism to check whether the entry that is being skipped is needed or not. I think that there could be situations in which the information that is being omitted here is crucial.

Say for example that we have 4 packages A, B, C, D. Say that A had possible versions: 1, 2, uninstalled. Say that B,C,D all have compatibility constraints with A:
* B is only compatible with requires *, i.e. 1 or 2
* C is only compatible with 1 or uninstalled
* D is only compatible with 2 or uninstalled

Thus, A has no versions left. If you hadn't seen the log from B, you wouldn't know why.
The last two situations may arise if C is allowed different versions, only some of which depend on (a specific version of) A.
Admittedly, this is not a common scenario, but I don't think it's impossible.

**Pull request merged**
