### PR TITLE
Cleanup most temporary dirs, fix #704, fix #723.

### LINKED ISSUE #704: Polluting /tmp
Starting from version 0.7/1.0, after adding/updating packages, several randomly named empty folders are left behind in `/tmp`, such as:
```
/tmp/TwOJH2Hzmugb
/tmp/ngcKCsSKTqbo
/tmp/5smw1tKbkzNt
...
```
It would be nice to have them automatically removed.

### LINKED ISSUE #723: Pkg doesn't clean up after tests properly
Leftovers after many builds on FreeBSD buildbot:

https://gist.githubusercontent.com/iblis17/5e496c9201cdcc77c29925382e144c73/raw/fd1dd35fc7e733169e131d941f682256e7b7f19f/tree.dump

### PR DESCRIPTION
**Pull request by fredrikekre**
bors try

### CODE REVIEW

**Comment by fredrikekre** [comment]
borst try

**Comment by fredrikekre** [comment]
bors try

**Comment by fredrikekre** [comment]
From AV:
```
SystemError (with C:\Users\appveyor\AppData\Local\Temp\1\jl_5912.tmp\machine2): rmdir: Permission denied
```

**Comment by fredrikekre** [comment]
Any idea why we don't have permission to rm tempdirs we create ourselves?

**Comment by StefanKarpinski** [comment]
On Windows if there's an open handle to anything, you can't delete it. Silly Windows.

**Comment by fredrikekre** [comment]
bors try

**Comment by KristofferC** [comment]
One way to diagnose this would be to instrument a local julia version to throw an error if a file is closed by a finalizer instead of explicitly (with e.g. a `do` block). The same for a git object. Should be fairly easy then to see if we are accidentally keeping things open.

**Comment by fredrikekre** [comment]
I am pretty sure it is the one I commented out here though. We are trying to remove the folder we are currently in.

**Comment by KristofferC** [comment]
Hm, why is this not getting merged?

**Pull request merged**
