### PR TITLE
Tweak test dep docs

### PR DESCRIPTION
**Pull request by IanButterworth**
Alternative proposal to https://github.com/JuliaLang/Pkg.jl/pull/3533
Closes https://github.com/JuliaLang/Pkg.jl/issues/3535

### CODE REVIEW

**Comment by IanButterworth** [comment]
It'd be good to get a 2nd opinion from a Pkg dev here, particularly marking the `test/Project.toml` as an "alternative", which is a bit of a demotion based on discussions like https://github.com/JuliaLang/Pkg.jl/issues/1788

**Comment by gdalle** [comment]
I think it's fair but I understand the hesitation

**Comment by lgoettgens** [comment]
Should this change imply a deprecation of the `test/Project.toml` approach? If yes, I would like to see a PSA about this, and maybe some motivation behind this change. I would like to understand, why the reasons that this approach was introduced in julia 1.2 are no longer valid to keep it around.
Furthermore, I wish for a *documented* way of integrating other sub-projects, most notably `docs/Project.toml` into the main `Project.toml` file.

**Comment by IanButterworth** [comment]
Both approaches are valid. Just that the docs used to be worded in a way that made it seem like `test/Project.toml` was the new better way.

It's better to characterize it as an experimental way with caveats, caveats that were originally documented.

There's nothing wrong with using either, just that the docs now make it clearer that `test/Project.toml` has caveats and isn't a replacement.

**Pull request merged**
