### PR TITLE
Fix parser (lexer)

### LINKED ISSUE #516: pkg> ?dev
It would be nice if this worked (in addition to `pkg> help dev`):
```
(v0.7) pkg> ?dev
ERROR: invalid command: "?dev"
```

I feel like it did at some point.

Edit: It is `pkg> ? dev` that works. Would still be nice to support this if possible, since you request help without the space in the regular julia REPL.

### PR DESCRIPTION
**Pull request by 00vareladavid**
Should fix #516

### CODE REVIEW

**Comment by KristofferC** [comment]
Can we add a test for #516?

**Comment by 00vareladavid** [comment]
Sure!

**Comment by KristofferC** [comment]
Thanks

**Comment by 00vareladavid** [comment]
Welcome!

**Pull request merged**
