### PR TITLE
CI: Increase the CI timeout. Update actions. Fix double precompilation.

### PR DESCRIPTION
**Pull request by DilumAluthge**
One of the Windows CI jobs keeps timing out, but when you look at the log, the tests have already passed, and it's just timing out because it's taking a long time cleaning up all the temp files and folders.

So let's see if increasing the timeout by 10 minutes gives it enough time to cleanup the temp files.

### CODE REVIEW

**Comment by IanButterworth** [comment]
The tests job takes 60 mins. Based on https://github.com/JuliaLang/Pkg.jl/actions/runs/6529785018/job/17727975783?pr=3665 that breaks down as
- 3 mins to start julia ?!
- 8 mins git cloning General
- 40 mins running tests
- 5 mins deleting temp files before close

On the first point, I just turned loading debug on to check it's not re-precompiling stdlibs

**Comment by IanButterworth** [comment]
Hope you don't mind me taking this over. LGTM now

**Review by DilumAluthge — COMMENTED** [review]
LGTM.

**Comment by DilumAluthge** [comment]
Thanks so much Ian!

**Comment by DilumAluthge** [comment]
Hmmm, one of the Windows jobs on this PR still timed out at 70 minutes.

**Comment by IanButterworth** [comment]
There will always be outliers. tbh, the root issue needs fixing, not just longer timeout

**Comment by DilumAluthge** [comment]
Do we know what the root issue is here?

**Pull request merged**
