### PR TITLE
show the exception when download fails in artifact downloading

### PR DESCRIPTION
**Pull request by KristofferC**
also, verify the tree hash on windows which I think (correct me if I am wrong @staticfloat) should be ok now.

Might have a bit of overlap with https://github.com/JuliaLang/Pkg.jl/pull/2355.

### CODE REVIEW

**Comment by staticfloat** [comment]
Yeah, this looks good to me.

**Review by staticfloat — APPROVED** [review]

**Comment by KristofferC** [comment]
Hmm...

```
┌ Error: failed to download tarball from "https://pkg.julialang.org/artifact/69a468bd51751f4ed7eda31c240e775df06d6ee6"
│   exception = HTTP/1.1 404 Not Found while requesting https://pkg.julialang.org/artifact/69a468bd51751f4ed7eda31c240e775df06d6ee6
└ @ Pkg.Artifacts C:\projects\pkg-jl\src\Artifacts.jl:321
ERROR: LoadError: could not load library "C:\Users\appveyor\AppData\Local\Temp\1\jl_pWD6Uf\artifacts\444cecb70ff39e8961dd33e230e151775d959f37\bin\libc_simple.dll"
Access is denied. 
```

on Win CI

**Comment by KristofferC** [comment]
Could it be something in `create_artifact`? I think that does something with the permissions.

**Comment by StefanKarpinski** [comment]
The trouble with this is that sometimes we try the package server for things that we really ought to know it doesn't have and this will make that pretty noisy. Perhaps that's better, but to do this really correctly is more subtle.

**Comment by KristofferC** [comment]
Hm, yeah that's true. Perhaps only show if it is not a 404?

**Comment by StefanKarpinski** [comment]
That's a pretty good approximation of what we want, yeah. That will miss cases where the pkg server should have something but for some reason doesn't, but it's still better in 99% of cases.

**Comment by staticfloat** [comment]
That's weird..... I tried to instrument the download part and it didn't print.  We aren't caching artifacts somewhere are we?

**Comment by staticfloat** [comment]
I've been trying to debug this; the fundamental error is that the owner of the file (`appveyor`) isn't getting the permissions it's supposed to.  While trying to reproduce locally however, I ran into another error:

```
julia> mktempdir() do dir
       mkdir(joinpath(dir, "foo"))
       symlink("foo", joinpath(dir, "link"))
       stat(joinpath(dir, "link"))
       end
ERROR: IOError: stat("C:\\Users\\Administrator\\AppData\\Local\\Temp\\jl_7nHqNZ\\link"): permission denied (EACCES)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:97 [inlined]
 [2] stat(path::String)
   @ Base.Filesystem .\stat.jl:69
 [3] (::var"#5#6")(dir::String)
   @ Main .\REPL[3]:4
 [4] mktempdir(fn::var"#5#6", parent::String; prefix::String)
   @ Base.Filesystem .\file.jl:729
 [5] mktempdir(fn::Function, parent::String)
   @ Base.Filesystem .\file.jl:727
 [6] top-level scope
   @ REPL[3]:1
```

This is breaking one of the earlier tests in Artifacts.  Basically, relative symlinks to directories don't seem to be working on windows.  I have no idea why this isn't causing problems on Appveyor.  I'm cooked for today, but I think we're going to have to fix this sooner than later.

**Comment by DilumAluthge** [comment]
I rebased this on master, so we can look at the Windows test results on both GHA and AppVeyor. cc: @ianshmean

**Comment by IanButterworth** [comment]
The conflict with master is a little messy here for me to understand, perhaps @staticfloat or @KristofferC, would you mind resolving conflicts?

**Comment by KristofferC** [comment]
I think this has been subsumed by https://github.com/JuliaLang/Pkg.jl/pull/2964

**Pull request closed without merging**
