### PR TITLE
`rm` should always preserve `julia` compat

### LINKED ISSUE #1407: failure to preserve compat entries for Julia itself
When removing a package from a project, any packages that are no longer in `[deps]` or `[extras]` get deleted from `[compat]`, which is all well and good, but this seems to be applied to any `julia` entry that might be in there as well, which we should keep since there is always an implicit dependency on `julia`. To reproduce:

1. Manually put a `julia = "1.3"` entry in the `[compat]` section.
2. Add any package, say `] add JSON`.
3. Remove that package: `] rm JSON`.
4. Now the `julia = "1.3"` entry has been deleted.

### PR DESCRIPTION
**Pull request by 00vareladavid**
---
fix #1407
caused by #1324

### CODE REVIEW

**Comment by 00vareladavid** [comment]
This makes me wonder, is declaring `compat` on packages which are not direct dependencies useful?

**Comment by DilumAluthge** [comment]
> This makes me wonder, is declaring compat on packages which are not direct dependencies useful?

Yeah. E.g. I want to specify compat for test dependencies

**Comment by StefanKarpinski** [comment]
Agree, one should probably be allowed to declare compat with anything in `[extras]` as well.

**Comment by KristofferC** [comment]
You are allowed to do that and it will be active when the target is run (i.e. when testing).

**Comment by StefanKarpinski** [comment]
That's not what the logic in this PR looks like it's doing—it looks like it's deleting compat for anythign that's not in `[deps]` but maybe I'm misunderstanding the logic...

**Comment by KristofferC** [comment]
Oh, yeah, if that happens, then it is a bug.

**Comment by fredrikekre** [comment]
Registrator doesn't allow it I think.

**Comment by StefanKarpinski** [comment]
If so then that should be fixed too. Why does registrator have an opinion about it...

**Pull request merged**
