### PR TITLE
fix rm: `project.extras` also contains dependency names

### LINKED ISSUE #876: Pkg sometimes removes [targets]
Sometimes the
```
[targets]
test = ["Test"]
```
section is removed from the `Project.toml` file. I have not been able to understand why, and I have always thought that "Well, I guess I accidentally removed it then...", but it keeps happening and it has driven me crazy! I HAVE NOT REMOVED IT!!

I have finally found a way to reproduce it:
1. Start with a clean clone of Pkg or `git clean -fdx` notably to remove the Manifest.toml file.
2. Remove the `uuid = ` section in Pkg
3. Run `julia --project` in the Pkg directory
4. Run `using Pkg` (this seems to be important ...)
5. `pkg> add Example`
6. `pkg> rm Example`

and then you have the following diff for the `Project.toml` file:

```diff
diff --git a/Project.toml b/Project.toml
index ed4c5a3..006b005 100644
--- a/Project.toml
+++ b/Project.toml
@@ -16,6 +16,3 @@ UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
 
 [extras]
 Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
-
-[targets]
-test = ["Test"]
```

### PR DESCRIPTION
**Pull request by 00vareladavid**
fixes #876 

Thanks @fredrikekre for getting it down to a minimal repro.

### CODE REVIEW

**Comment by 00vareladavid** [comment]
bors try

**Comment by fredrikekre** [comment]
Add a test?

**Comment by 00vareladavid** [comment]
Sorry about that! :sweat_smile: I didn't know you would end up getting pinged.

**Comment by oxinabox** [comment]
Can this get backported?
It is really annoying.
(@nickrobinson251  reproduced the error in 1.0.3.)

**Comment by fredrikekre** [comment]
It has the label so yea it will.

**Comment by oxinabox** [comment]
I should have said: Can we have it to be backported ASAP, and a patch release tagged early,
it is _really_ annoying

**Comment by fredrikekre** [comment]
You can help debug https://github.com/JuliaLang/julia/pull/30954

**Pull request merged**
