### PR TITLE
Allow optional dependencies in the resolver (without changing VersionSet)

### LINKED ISSUE #3125: Resolver feature request: compatibility on optional dependencies
@carlobaldassi, we are thinking about possible ways of adding conditional dependencies. In almost all cases it seems there is a need for a package to be able to add compatibility to a package that does not have to end up getting installed.

So as an example:

```toml
[deps]
A = "..."
B = "..."

[weakdeps]
C = "..."

[compat]
A = "0.1"
B = "0.2"
C = "0.3"
```

In this case, we want to require `C` to have the `"0.3"` compat *if the package C ends up getting installed*.  But if it happens that C does not get installed, then that is also fine.

How hard do you think something like that would be to implement. And do you see any immediate problems conceptually by such a thing?

I guess one question is how much score you give C being installed vs the score of upgrading other versions (that might be on lower versions if C is installed). But the existing resolver already have to deal with questions like that I guess.

### PR DESCRIPTION
**Pull request by carlobaldassi**
This closes #3125 and it's an alternative implementation to #3204.
It does not change `VersionSet` so it does not have any of the associated difficulties there. 
It adds a keyword argument to the `GraphType` constructor instead ([here](https://github.com/carlobaldassi/Pkg3.jl/blob/56f5fdc9419b3a9ddc10cac5f73dc6da05d55734/src/Resolve/graphtype.jl#L245)). The type is `Dict{UUID,Dict{VersionNumber,Set{UUID}}}`.
@KristofferC this is what was discussed [here](https://github.com/JuliaLang/Pkg.jl/pull/3204#issuecomment-1251017819).
The building of the structure is a little cumbersome, an example can be seen [here](https://github.com/carlobaldassi/Pkg3.jl/blob/56f5fdc9419b3a9ddc10cac5f73dc6da05d55734/test/resolve_utils.jl#L76-L79).

This still needs testing, just as much as #3204 did.

### CODE REVIEW

**Comment by KristofferC** [comment]
Thanks, this is great to have!

**Comment by IanButterworth** [comment]
Yeah. Thanks for both! It does seem like this is the better route.

**Comment by KristofferC** [comment]
Question, does the `Fixed` input to the resolver also need to distinguish between weak/strong dependencies? I would guess so..

**Comment by KristofferC** [comment]
@carlobaldassi, when adding support for the weak stuff in `Fixed`, I am hitting an assertion. It can be reprod with this Pkg commit (https://github.com/JuliaLang/Pkg.jl/commit/167cd57f93eb0daa854ed19b1b6a5a68618db937) using the following script:

```julia
using Pkg
using LibGit2
Pkg.activate(; temp=true)
tmp = mktempdir()
cd(tmp)
LibGit2.clone("https://github.com/IanButterworth/WeakDepsExamples", "WeakDepsExamples")
Pkg.develop(path="WeakDepsExamples/HasWeakDeps.jl")
```

The assertion is:

```julia
julia> Pkg.develop(path="WeakDepsExamples/HasWeakDeps.jl")
   Resolving package versions...
ERROR: AssertionError: !((gconstr[rp0])[end])
Stacktrace:
  [1] log_event_req!(graph::Pkg.Resolve.Graph, rp::Base.UUID, rvs::Pkg.Versions.VersionSpec, reason::Tuple{Base.UUID, Pkg.Resolve.ResolveLogEntry})
    @ Pkg.Resolve ~/JuliaPkgs/Pkg.jl/src/Resolve/graphtype.jl:678
  [2] _add_reqs!(graph::Pkg.Resolve.Graph, reqs::Dict{Base.UUID, Pkg.Versions.VersionSpec}, reason::Tuple{Base.UUID, Pkg.Resolve.ResolveLogEntry}; weak_reqs::Set{Base.UUID})
    @ Pkg.Resolve ~/JuliaPkgs/Pkg.jl/src/Resolve/graphtype.jl:399
  [3] _add_fixed!(graph::Pkg.Resolve.Graph, fixed::Dict{Base.UUID, Pkg.Resolve.Fixed})
    @ Pkg.Resolve ~/JuliaPkgs/Pkg.jl/src/Resolve/graphtype.jl:428
  [4] Pkg.Resolve.Graph(compat::Dict{Base.UUID, Dict{VersionNumber, Dict{Base.UUID, Pkg.Versions.VersionSpec}}}, compat_weak::Dict{Base.UUID, Dict{VersionNumber, Set{Base.UUID}}}, uuid_to_name::Dict{Base.UUID, String}, reqs::Dict{Base.UUID, Pkg.Versions.VersionSpec}, fixed::Dict{Base.UUID, Pkg.Resolve.Fixed}, verbose::Bool, julia_version::VersionNumber)
    @ Pkg.Resolve ~/JuliaPkgs/Pkg.jl/src/Resolve/graphtype.jl:342
  [5] deps_graph(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, uuid_to_name::Dict{Base.UUID, String}, reqs::Dict{Base.UUID, Pkg.Versions.VersionSpec}, fixed::Dict{Base.UUID, Pkg.Resolve.Fixed}, julia_version::VersionNumber)
    @ Pkg.Operations ~/JuliaPkgs/Pkg.jl/src/Operations.jl:537
  [6] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::VersionNumber)
```

If I disable the assertion, things work as I expect for my limited testing but not sure if something else will blow up at some point.

The only thing that commit does is that it passes a ` Set([UUID("6fe1bfb0-de20-5000-8ca7-80f57d26f881")]))` to the `Fixed` constructor for the package being developed (because that is a weak dep for the package: https://github.com/IanButterworth/WeakDepsExamples/blob/adb19bec21d763566c4419bf1d459fcf130ee9ae/HasWeakDeps.jl/Project.toml#L9).

Any ideas?

**Comment by carlobaldassi** [comment]
@KristofferC you're right, that assert is no longer correct. The good news is, it can be safely disabled just like you did in the next commit, or one can keep it around writing `reason ≡ :explicit_requirement && @assert !gconstr[rp0][end]` as I did in this branch.

**Comment by DilumAluthge** [comment]
Are the `@assert`s here being used for debugging purposes only, or are they necessary to ensure correctness? If the latter, they should be switched to explicit errors, right? Since we'll eventually disable `@assert` by default in Julia.

**Comment by carlobaldassi** [comment]
They're purely for debugging.

**Comment by carlobaldassi** [comment]
I have pushed a better fix now, that also fixes the logging (that assert was in fact signalling an assumption about the code below after all...)

**Pull request merged**
