### PR TITLE
disable PRs, we use bors

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
bors try

**Comment by KristofferC** [comment]
bors ping

**Comment by KristofferC** [comment]
bors try

**Comment by KristofferC** [comment]
bors try

**Comment by fredrikekre** [comment]
bors delegate+

**Comment by fredrikekre** [comment]
bors: try

**Comment by KristofferC** [comment]
bors try

**Comment by vchuravy** [comment]
bors try

**Comment by KristofferC** [comment]
bors try

**Comment by KristofferC** [comment]
bors try

**Comment by KristofferC** [comment]
bors ping

**Comment by KristofferC** [comment]
bors try

**Comment by fredrikekre** [comment]
https://github.com/bors-ng/bors-ng/issues/445

**Comment by notriddle** [comment]
bors try

**Comment by KristofferC** [comment]
bors try

**Comment by KristofferC** [comment]
bors +r

**Pull request merged**
