### PR TITLE
Remove support for "meta options"

### PR DESCRIPTION
**Pull request by 00vareladavid**
Both `--env` and `--preview` were around before. But `activate` was perfered to `--env`. And the only documented syntax for preview is `preview add Plots`.

In light of this, no real use for "meta options" anymore.

### CODE REVIEW

**Comment by 00vareladavid** [comment]
bors try

**Comment by 00vareladavid** [comment]
bors try

**Comment by 00vareladavid** [comment]
bors try

**Comment by 00vareladavid** [comment]
Ok to merge? Its mostly just dead code

**Comment by StefanKarpinski** [comment]
Go for it.

**Pull request merged**
