### PR TITLE
Don't update registry when developing a local path

### PR DESCRIPTION
**Pull request by fredrikekre**
Well, that was easier than I thought... (fingers crossed for CI)

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
What happens if you develop a local path and it causes some new package to be installed? We still want to update the registry if it hasn't be previously updated in that situation, right?

**Comment by fredrikekre** [comment]
TBH didn't think too much about this, I was just getting really frustrated how useless the package manager was without an internet connection.

**Comment by StefanKarpinski** [comment]
Maybe also an "offline" mode for not trying to connect to the internet at all?

**Comment by fredrikekre** [comment]
Yea, it is probably better to tackle this with something like that. The tricky thing would be resolving I imagine, since only package versions that are already downloaded should be considered, no matter what the registry says.

**Comment by StefanKarpinski** [comment]
Well, to be clear I think we should do this too—the package manager should only hit the internet when it needs to and to add a local package it doesn't need to.

**Comment by KristofferC** [comment]
There is a bug now where it actually throws when it fails to update the registry. It is because we are throwing a different error than before so the code fails to catch it.

**Pull request merged**
