### PR TITLE
Add `start` command to REPL API

### PR DESCRIPTION
**Pull request by 00vareladavid**
I figure most people issue a `cd` after `generate` when starting a new project (at least that's what makes sense to me, why would you create a project and then go do something else?). From a usability standpoint, it makes sense to provide a command to do both. Thoughts?

Note: this PR is just for reference, I don't know what your policy is and I didn't do extensive testing.

### CODE REVIEW

**Comment by KristofferC** [comment]
Hm, it seems a bit excessive to have a completely new command that only provides a `cd`. We could think about defaulting to cd into the new package but I don't think there should be a completely separate verb for it.

**Comment by 00vareladavid** [comment]
Best left as an issue for later

**Comment by fredrikekre** [comment]
We could make `generate Foo` do an implicit `activate Foo` withouth `cd`ing to it. This would be similar to `init` (although there we create the project in `pwd()`).

**Comment by StefanKarpinski** [comment]
It very much seems like these could be combined somehow...

**Comment by 00vareladavid** [comment]
That makes sense to me.
The workflow I was thinking of is: `generate Foo` followed by `add Example`.
My gut reaction was that the `add` would apply to the environment I most recently  handled (which would be `Foo`).

#418 is also relevant, they wanted to do a `generate Foo` followed by `import Foo`. Activating the environment would also make this workflow possible.

**Comment by 00vareladavid** [comment]
Actually, I though about #418 some more and the best fix for that seems to add a flag to `dev`. E.g. `dev --generate`. 

`generate Foo` could be used if the focus is `Foo`.

`dev --generate Foo` can be used if you wish to add a dependency which does not exist yet (the focus would remain on the current environment). `dev --generate Foo` would not `activate Foo` and so the defaults would reflect the intended workflow.

**Pull request closed without merging**
