### PR TITLE
Some refactoring of submodules

### PR DESCRIPTION
**Pull request by KristofferC**
Something weird happened with #1357

### CODE REVIEW

**Comment by KristofferC** [comment]
bors retry

**Comment by KristofferC** [comment]
compress is in Registrator: https://github.com/JuliaRegistries/Registrator.jl/blob/e16dee52bbd9b2d5ff87f34546199fe0c32afc7f/src/regedit/register.jl#L154-L214

**Comment by KristofferC** [comment]
But you could of course always load the compress module with `include` and  `pathof(Pkg)`

**Comment by staticfloat** [comment]
the function is, but it still attempts to import `Pkg.Compress`:

```
https://github.com/JuliaRegistries/Registrator.jl/blob/e16dee52bbd9b2d5ff87f34546199fe0c32afc7f/src/regedit/register.jl#L190
```

**Pull request merged**
