### PR TITLE
CI: Don't use the Pkg server when building the docs

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Why?

**Comment by StefanKarpinski** [comment]
Because it's been flaky? Or is it because it's not sufficiently up-to-date?

**Comment by DilumAluthge** [comment]
> Because it's been flaky? Or is it because it's not sufficiently up-to-date?

The former. Docs builds are intermittently failing because of Pkg server flakiness.

**Comment by StefanKarpinski** [comment]
Until we can fix the reliability of the pkg servers this is fine. Once we do that, we should revert this.

**Comment by fredrikekre** [comment]
What is the failure mode? It is not like we need the most up-to-date registry here so this would only be used when the server is completely dead, and even then, don't we fall back to the old methods?

**Comment by DilumAluthge** [comment]
Here's an example: https://github.com/JuliaLang/Pkg.jl/runs/1444642614?check_suite_focus=true

For some reason it didn't fall back, it just errored out.

**Pull request closed without merging**
