### PR TITLE
Don't mutate project.deps during project write

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3327

~Fixes parts of Pkg that weren't aware of the way that weakdeps can be listed in both `[weakdeps]` and `[deps]`.~
Actually was just an unwanted mutation of `project.deps` during writing the project out.

The mwe here now works https://github.com/JuliaLang/Pkg.jl/issues/3327#issuecomment-1547690361 
```
shell> cd foo
/Users/ian/Documents/GitHub/julia/foo

shell> git clone http://github.com/BioJulia/BioSymbols.jl
...

shell> cd BioSymbols.jl
/Users/ian/Documents/GitHub/julia/foo/BioSymbols.jl

shell> git clone http://github.com/BioJulia/FASTX.jl
...

(Pkg) pkg> activate FASTX.jl
  Activating project at `~/Documents/GitHub/julia/foo/BioSymbols.jl/FASTX.jl`

(FASTX) pkg> add .
    Updating git-repo `/Users/ian/Documents/GitHub/julia/foo/BioSymbols.jl`
   Resolving package versions...
    Updating `~/Documents/GitHub/julia/foo/BioSymbols.jl/FASTX.jl/Project.toml`
  [67c07d97] + Automa v1.0.0
  [47718e42] + BioGenerics v0.1.2
  [3c28c6f8] + BioSymbols v5.1.3 `..#master`
  [aea7be01] + PrecompileTools v1.1.2
  [354b36f9] + StringViews v1.3.3
  [3bb67fe8] + TranscodingStreams v0.9.13
    Updating `~/Documents/GitHub/julia/foo/BioSymbols.jl/FASTX.jl/Manifest.toml`
  [67c07d97] + Automa v1.0.0
  [47718e42] + BioGenerics v0.1.2
  [3c28c6f8] + BioSymbols v5.1.3 `..#master`
  [aea7be01] + PrecompileTools v1.1.2
  [21216c6a] + Preferences v1.4.0
  [354b36f9] + StringViews v1.3.3
  [3bb67fe8] + TranscodingStreams v0.9.13
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [b77e0a4c] + InteractiveUtils
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [de0858da] + Printf
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [fa267f1f] + TOML v1.0.3
  [8dfed614] + Test
  [4ec0a83e] + Unicode
     Warning The project dependencies or compat requirements have changed since the manifest was last resolved. It is recommended to `Pkg.resolve()` or consider `Pkg.update()` if necessary.
┌ Warning: The project dependencies or compat requirements have changed since the manifest was last resolved.
│ It is recommended to `Pkg.resolve()` or consider `Pkg.update()` if necessary.
└ @ Pkg.API ~/Documents/GitHub/Pkg.jl/src/API.jl:1761
Precompiling project...
  1 dependency successfully precompiled in 2 seconds. 8 already precompiled.

(FASTX) pkg> 
```

### CODE REVIEW

**Comment by KristofferC** [comment]
If a dep is listed in both `[deps]` and `[weakdeps]` then (AFAIU) it should be ignored from deps. The code here is meant to take care of that:

https://github.com/JuliaLang/Pkg.jl/blob/f4d64d2c741173f1b4431da7902987887ae357c1/src/project.jl#L136

Is there an issue with that approach?

**Comment by IanButterworth** [comment]
Kristoffer suggested this latest fix so should be good to go

**Comment by jishnub** [comment]
Has this been included in Julia v1.9.3? I see the `stat_rep` issue on Julia v1.9.3 in https://github.com/JuliaArrays/OffsetArrays.jl/actions/runs/6022728726/job/16338079285?pr=331

**Comment by pkofod** [comment]
> No it will be in 1.9.4

much appreciated, this is quite annoying when developing extensions (though they are very useful, so I can live with it :) )

**Pull request merged**
