### PR TITLE
only update registries in first depot path

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
So I rethought this a bit—what if we update any registry that we have write access to? Would that be better? We should always be able to write `DEPOT_PATH[1]` but that rule would work no matter what.

**Comment by fredrikekre** [comment]
What is the correct way to check that a directory is writeable?

**Comment by StefanKarpinski** [comment]
That's a good question... I think it's a combination of querying the user and stat flags.

**Comment by fredrikekre** [comment]
That much I figured out on my own, hoped someone would know the combination :slightly_smiling_face:

**Comment by StefanKarpinski** [comment]
I'm working on something. Will report back 😸

**Comment by fredrikekre** [comment]
Merge this for now, or wait until we have a real solution?

**Comment by StefanKarpinski** [comment]
Go for it. I couldn’t even figure out a correct way to get libuv to tell you who the current user is. So 🤷🏼‍♂️

**Comment by simonbyrne** [comment]
Note that this still fails if the user calls `] build`

**Comment by fredrikekre** [comment]
Example?

**Comment by simonbyrne** [comment]
```
using Pkg

envdir = mktempdir()

depot1 = mktempdir()
depot2 = mktempdir()

Pkg.activate(envdir)

resize!(DEPOT_PATH, 1)
DEPOT_PATH[1] = depot2
Pkg.add("Arpack")

resize!(DEPOT_PATH, 2)
DEPOT_PATH[1] = depot1
DEPOT_PATH[2] = depot2
Pkg.add("Rmath")

Pkg.build() # this works

run(`chmod -R ugo-w $depot2`)

Pkg.build() # this fails
```

```
julia> Pkg.build() # fails
  Building Arpack → `/var/folders/50/q7_qvjks4c5dj_51zd0cp4cw0000gn/T/tmpkcDoqm/packages/Arpack/cu5By/deps/build.log`
ERROR: SystemError: opening file "/var/folders/50/q7_qvjks4c5dj_51zd0cp4cw0000gn/T/tmpkcDoqm/packages/Arpack/cu5By/deps/build.log": Permission denied
Stacktrace:
 [1] #systemerror#43(::Nothing, ::Function, ::String, ::Bool) at ./error.jl:134
 [2] systemerror at ./error.jl:134 [inlined]
 [3] #open#309(::Nothing, ::Nothing, ::Nothing, ::Bool, ::Nothing, ::Function, ::String) at ./iostream.jl:283
 [4] #open at ./none:0 [inlined]
 [5] open(::String, ::String) at ./iostream.jl:339
 [6] #open#310(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::getfield(Pkg.Operations, Symbol("##52#57")){Bool,Cmd}, ::String, ::Vararg{String,N} where N) at ./iostream.jl:367
 [7] open at ./iostream.jl:367 [inlined]
 [8] (::getfield(Pkg.Operations, Symbol("##51#56")){Bool,String,Cmd,String})() at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1060
 [9] #53 at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1080 [inlined]
 [10] #41 at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:898 [inlined]
 [11] withenv(::getfield(Pkg.Operations, Symbol("##41#46")){getfield(Pkg.Operations, Symbol("##53#58")){getfield(Pkg.Operations, Symbol("##51#56")){Bool,String,Cmd,String}},Pkg.Types.Context}, ::Pair{String,String}, ::Vararg{Pair{String,B} where B,N} where N) at ./env.jl:148
 [12] (::getfield(Pkg.Operations, Symbol("##40#44")){Bool,getfield(Pkg.Operations, Symbol("##53#58")){getfield(Pkg.Operations, Symbol("##51#56")){Bool,String,Cmd,String}},Pkg.Types.Context,Pkg.Types.PackageSpec,Pkg.Types.Context})(::String) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:897
 [13] mktempdir(::getfield(Pkg.Operations, Symbol("##40#44")){Bool,getfield(Pkg.Operations, Symbol("##53#58")){getfield(Pkg.Operations, Symbol("##51#56")){Bool,String,Cmd,String}},Pkg.Types.Context,Pkg.Types.PackageSpec,Pkg.Types.Context}, ::String) at ./file.jl:581
 [14] mktempdir at ./file.jl:579 [inlined]
 [15] #with_dependencies_loadable_at_toplevel#38(::Bool, ::Function, ::getfield(Pkg.Operations, Symbol("##53#58")){getfield(Pkg.Operations, Symbol("##51#56")){Bool,String,Cmd,String}}, ::Pkg.Types.Context, ::Pkg.Types.PackageSpec) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:853
 [16] #with_dependencies_loadable_at_toplevel at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:0 [inlined]
 [17] #build_versions#48(::Bool, ::Bool, ::Function, ::Pkg.Types.Context, ::Array{Base.UUID,1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1078
 [18] #build_versions at ./none:0 [inlined]
 [19] #build#59(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:377
 [20] build at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:352 [inlined]
 [21] #build#58 at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:350 [inlined]
 [22] build at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:350 [inlined]
 [23] #build#55 at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:347 [inlined]
 [24] build() at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:347
 [25] top-level scope at none:0
```

**Comment by fredrikekre** [comment]
That is unrelated to registry updating though. Perhaps raise a separate issue about this? Maybe we shouldn't try to re-build packages that are installed in other depots either or something...

**Pull request merged**
