### PR TITLE
Fix `safe_realpath` for shared network drives

### PR DESCRIPTION
**Pull request by ckingdon95**
See discussion here:
https://github.com/JuliaLang/julia/issues/33956

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I guess the question is does this fix the issue for you?

**Comment by ckingdon95** [comment]
Yes! I can now activate environments on my network drive. I'm not sure if there are other cases though that I should test out

**Comment by ckingdon95** [comment]
Actually, I spoke too soon. The activation works, but trying to do a `status` or using one of the packages from the environment results in the same error. I will look at where these other calls to `realpath` are coming from.

**Comment by ckingdon95** [comment]
Unfortunately, the line causing these next errors is in julia base, not in Pkg. here: https://github.com/JuliaLang/julia/blob/master/base/loading.jl#L120

The function `dummy_uuid` is being called when I do a `Pkg.status` or when I try to use a package in the environment. It calls `realpath` on the project file, which in my case is on the shared network drive.

**Comment by StefanKarpinski** [comment]
Exciting! You get to make a PR to Base 😀. It would be fine for that function to do something similar, i.e. wrap the call to `realpath` in a try catch and just use `project_path` if `realpath` fails.

**Comment by StefanKarpinski** [comment]
I've approved but, @ckingdon95, I need you to make this no longer a draft before I can merge.

**Comment by ckingdon95** [comment]
@StefanKarpinski should we be concerned about the one failing Travis build on this one?

**Comment by StefanKarpinski** [comment]
It doesn't look related, but I've restarted it just to be sure.

**Comment by fredrikekre** [comment]
I wonder if we should do this Windows only. Maybe doesn't matter.

**Comment by davidanthoff** [comment]
It would actually be interesting to know if one uses a Linux/Mac client to access the same network share... But that probably shouldn't hold up this PR, right?

**Pull request merged**
