### PR TITLE
no need to execute sh stuff for Pkg

### LINKED ISSUE #345: 'No sh engine found...'
Copied from discourse:

Hi, I built the latest (yesterday) master of Julia and am struggling to get Pk3 up and running. I’m on Win10 and it can’t find a program to run sh files:

```julia
(v0.7) pkg> develop Tokenize
  Updating git-repo `https://github.com/KristofferC/Tokenize.jl.git`
┌ Warning: packages will require to have a [Julia]Project.toml file in the future
└ @ Pkg.Types Types.jl:817
[ Info: Path `C:\Users\zacnu\.julia\dev\Tokenize` exists and looks like the correct package, using existing path instead of cloning
 Resolving package versions...
ERROR: No sh engines found. We looked for: E:\cygin64\home\zacnu\julia7\usr\bin\busybox.exe, sh. Install one and ensure it is available on the path.

Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] #probe_platform_engines!#14(::Bool, ::Function) at E:\cygin64\home\zacnu\julia7\usr\share\julia\stdlib\v0.7\Pkg\src\PlatformEngines.jl:346
 [3] probe_platform_engines! at E:\cygin64\home\zacnu\julia7\usr\share\julia\stdlib\v0.7\Pkg\src\PlatformEngines.jl:138 [inlined]
 [4] apply_versions(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Dict{Base.UUID,Base.SHA1}, ::Dict{Base.UUID,Array{String,1}}) at E:\cygin64\home\zacnu\julia7\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:464
 [5] apply_versions at E:\cygin64\home\zacnu\julia7\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:460 [inlined]
 [6] #add_or_develop#52(::Array{Base.UUID,1}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at E:\cygin64\home\zacnu\julia7\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:974
 [7] #add_or_develop at .\<missing>:0 [inlined]
 [8] #add_or_develop#8(::Symbol, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at E:\cygin64\home\zacnu\julia7\usr\share\julia\stdlib\v0.7\Pkg\src\API.jl:39
 [9] #add_or_develop at .\<missing>:0 [inlined]
 [10] do_add_or_develop!(::Pkg.Types.Context, ::Array{Union{Pkg.Types.VersionRange, String, Pkg.REPLMode.Command, Pkg.REPLMode.Option, Pkg.REPLMode.Rev},1}, ::Pkg.REPLMode.CommandKind) at E:\cygin64\home\zacnu\julia7\usr\share\julia\stdlib\v0.7\Pkg\src\REPLMode.jl:595
 [11] #invokelatest#1 at .\essentials.jl:670 [inlined]
 [12] invokelatest at .\essentials.jl:669 [inlined]
 [13] do_cmd!(::Array{Union{Pkg.Types.VersionRange, String, Pkg.REPLMode.Command, Pkg.REPLMode.Option, Pkg.REPLMode.Rev},1}, ::REPL.LineEditREPL) at E:\cygin64\home\zacnu\julia7\usr\share\julia\stdlib\v0.7\Pkg\src\REPLMode.jl:275
 [14] #do_cmd#8(::Bool, ::Function, ::REPL.LineEditREPL, ::String) at E:\cygin64\home\zacnu\julia7\usr\share\julia\stdlib\v0.7\Pkg\src\REPLMode.jl:235
 [15] do_cmd at E:\cygin64\home\zacnu\julia7\usr\share\julia\stdlib\v0.7\Pkg\src\REPLMode.jl:232 [inlined]
 [16] (::getfield(Pkg.REPLMode, Symbol("##27#30")){REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at E:\cygin64\home\zacnu\julia7\usr\share\julia\stdlib\v0.7\Pkg\src\REPLMode.jl:950
 [17] top-level scope
```

### PR DESCRIPTION
**Pull request by KristofferC**
Should fix #345

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Yes, you would have to rebuild Julia for this to take effect. Sorry!

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/27444 need to be merged first.

**Comment by ZacLN** [comment]
Ta

**Comment by staticfloat** [comment]
This has been fixed in `BinaryProvider` since March; https://github.com/JuliaPackaging/BinaryProvider.jl/commit/e9f8c4d232c9451f93a45be3135b4124a72f3f3f#diff-bc31fecc631ec0c23d226809fb26648b

I wish there was a way we didn't have to duplicate this code, and could have just a single version of it everywhere.

**Comment by StefanKarpinski** [comment]
There is: make BinaryProvider a stdlib and use the stdlib copy from Pkg.

**Comment by KristofferC** [comment]
Yes, this is indeed not ideal to not receive bug fixes to the original code, and I've been thinking about ways to solve it, but since it has worked it hasn't been a top priority in my head for the moment.

**Pull request merged**
