### PR TITLE
In `] st --outdated`, add a hint explaining that `] add Example@1.2.3` is the correct syntax for adding a package by version

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by IanButterworth** [comment]
For review could you elaborate what this looks like and why it's needed? Thanks!

**Comment by IanButterworth** [comment]
I assume `] add GLMakie#...` failed? Perhaps that's the place for a tip?

**Comment by DilumAluthge** [comment]
In this case, `] add GLMakie#...` did error, because the tag in question didn't exist on the repo in question. But in general, it may or may not error. E.g. `] add Example#v0.5.3` doesn't error.

**Comment by IanButterworth** [comment]
Yeah it seems to me like it's cleaner to not add what this PR currently adds but give a tip during errors for a failed `add Foo#1.2.3`. 
```
Error...
Info: It looks like you tried to install by version number. Use the form `add Foo@1.2.3` to add by version number, not by tag.
```

**Pull request closed without merging**
