### PR TITLE
WIP: support test-dependencies

### PR DESCRIPTION
**Pull request by KristofferC**
This allows one to write e.g.

```
[targets.test.deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

to load these only when testing.

WIP because the way TOML.jl prints this back in the Project file is something like:

```
[targets.test.deps]
    [targets.test]
        [targets.test.deps]
        Example = "7876af07-990d-54b4-ab0e-23690620f79a"
        Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

### CODE REVIEW

**Comment by omus** [comment]
Is this feature expected to work? I [added `Dates` as a test dependency](https://github.com/invenia/Mocking.jl/pull/48/commits/bd61417fa964aede4e006ebb6d94757741ec45de) and it was not installed ([Travis CI log](https://travis-ci.org/invenia/Mocking.jl/jobs/396562725#L496))

**Comment by KristofferC** [comment]
Thanks for report, I'll see what is happening.

**Comment by KristofferC** [comment]
Oh, I think this is fixed on nightly but that is run using the `alpha`?

**Comment by omus** [comment]
> Oh, I think this is fixed on nightly but that is run using the `alpha`?

That run was using the `alpha`. I'll test this again on the `nightly` now that I think I resolved the issue I was having there.

**Comment by omus** [comment]
Looks to be the same issue with the [nightly](https://travis-ci.org/invenia/Mocking.jl/jobs/396590200#L502). Should I make this into a new issue?

**Comment by KristofferC** [comment]
Sure, but it did add `Dates`

```
 Resolving package versions...
  Updating `/tmp/tmpRJCGF2/Project.toml`
  [78c3b35d] + Mocking v0.5.3 [`~/build/invenia/Mocking.jl`]
  [ade2ca70] + Dates <-----
```

Hmm.

**Comment by KristofferC** [comment]
I don't understand why it is trying to load `Dates` **into** `Mocking`.

**Comment by KristofferC** [comment]
Oh, I guess it is the 

```
function apply!(pe::PatchEnv, p::Patch)
    Core.eval(pe.mod, convert(Expr, p))
end
``´

that evaluates a `using Dates` into `Mocking` or something?

We should probably add the test deps to the `deps` of the package being tested instead of just to "toplevel".

**Comment by KristofferC** [comment]
Ok, I know what needs to be done here (https://github.com/JuliaLang/Pkg.jl/issues/427). Thanks for the report again.

**Comment by omus** [comment]
> that evaluates a using `Dates` into `Mocking` or something?

What's happening is `Dates` is being loaded into a dynamically created submodule. Mocking.jl is weird and I'm hoping it can just be a shell around Cassette in the future.

**Pull request merged**
