### PR TITLE
make telemetry file writing more likely to be atomic

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Alternative to https://github.com/JuliaLang/Pkg.jl/pull/1625. Write the telemetry file to a temp file and then move it into place.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
@fredrikekre do you have a situation where this was causing problems so we can see if this fixes it? Or should I just merge this and we can see if the problems persist?

**Comment by fredrikekre** [comment]
Btw, this doesn't solve what https://github.com/JuliaLang/Pkg.jl/pull/1625 tried to solve -- multiple tasks can still try to read the file at the same time, which was the problem.

**Comment by StefanKarpinski** [comment]
How doesn’t it? It writes the file in a temporary location and then moves it into place only once it’s complete. Assuming the mv operation is atomic, it should make it impossible to read a half-written file.

**Comment by StefanKarpinski** [comment]
However, we could apply that fix as well since it’s a much more graceful way to synchronize between different tasks in the same process. The temp file maneuver should fix the interprocess issue.

**Comment by fredrikekre** [comment]
The problem wasn't that a task read a file that was partially written by another, but when there was already a broken file on disk that multiple files read. But yea, good to have a look anyway I think, since otherwise all tasks would generate their own `client_uuid` and all tasks would display the legal notice etc.

**Comment by StefanKarpinski** [comment]
Clearly I didn't understand what your fix was for. Sorry about that. I included a version of your PR in https://github.com/JuliaLang/Pkg.jl/pull/1871 so that should address the problem in any case.

**Pull request merged**
