### PR TITLE
Use pathrepr in pkg> gc.

### PR DESCRIPTION
**Pull request by fredrikekre**
bors try

### CODE REVIEW

**Comment by KristofferC** [comment]
Cappening broke Pkg I think, we are fixing it :P

**Comment by fredrikekre** [comment]
Yea. This changes
```
(v1.0) pkg> gc
    Active manifests:
        `/home/fredrik/dev/Pkg/Manifest.toml`
        `/home/fredrik/.julia/environments/v1.0/Manifest.toml`
   Deleted `/home/fredrik/.julia/packages/JSON/BopYd`: 80.102 KiB
   Deleted 1 package installations : 80.102 KiB
```
to
```
(v1.0) pkg> gc
    Active manifests:
        `~/dev/Pkg/Manifest.toml`
        `~/.julia/environments/v1.0/Manifest.toml`
   Deleted `~/.julia/packages/JSON/BopYd` (80.102 KiB)
   Deleted 1 package installation (80.102 KiB)
```

**Comment by fredrikekre** [comment]
bors try

**Comment by fredrikekre** [comment]
bors try

**Comment by KristofferC** [comment]
Probably need https://github.com/JuliaLang/julia/pull/29315 here

**Comment by fredrikekre** [comment]
bors try

**Pull request merged**
