### PR TITLE
make Pkg.precompile fatal

### PR DESCRIPTION
**Pull request by simonbyrne**
Similar to #1851

### CODE REVIEW

**Comment by simonbyrne** [comment]
Any thoughts @KristofferC @StefanKarpinski?

**Comment by KristofferC** [comment]
Do you want it to throw as soon as possible (like with the current implementation) or try all packages and only throw in the end?

**Comment by simonbyrne** [comment]
Throw as soon as possible would be best, I think.

**Comment by KristofferC** [comment]
Alright, then lgtm.

**Comment by StefanKarpinski** [comment]
Similar to how I wanted build errors to just be fatal, why wouldn't precompile errors also just be fatal?

**Comment by StefanKarpinski** [comment]
If precompilation is broken for a package, shouldn't the recourse be either turning it off for that package or fixing it? This just seems like it enables people to have registered packages for which precompilation is broken but which nevertheless don't opt out of precompilation.

**Comment by simonbyrne** [comment]
I agree with that. WIll change to fail by default

**Comment by simonbyrne** [comment]
updated.

**Pull request merged**
