### PR TITLE
add two missing GC.@preserve calls

### PR DESCRIPTION
**Pull request by StefanKarpinski**
I believe these are necessary. @vtjnash, can you take a quick look and verify?

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
bors try

**Comment by StefanKarpinski** [comment]
Well, I have no idea what this error means:
```
ERROR: LoadError: LoadError: syntax: ssavalue with no def
...
in expression starting at /home/travis/build/JuliaLang/Pkg.jl/src/Types.jl:678
```

**Comment by StefanKarpinski** [comment]
bors try

**Comment by KristofferC** [comment]
Does just copy pasting this function into its own file reproduce. Could file a bug upstream then.

**Comment by StefanKarpinski** [comment]
It does; I'll do that.

**Comment by StefanKarpinski** [comment]
bors try

**Pull request merged**
