### PR TITLE
refactor `Pkg.status`

### LINKED ISSUE #277: Project deps not in a manifest are not printed in status.

### LINKED ISSUE #1528: disabling --diff on 1.3, bug?
Which part of the documentation am I overlooking when I think that in the following case it should not print the diff but the whole project.toml?
```julia
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8

(DataFrames) pkg> st
Project DataFrames v0.19.3
    Status `C:\Users\Matthis\.julia\dev\DataFrames\Project.toml`
  (no changes since last commit)
```

### PR DESCRIPTION
**Pull request by 00vareladavid**
This refactors the display code for `Pkg.status`. It seems it hasn't been reworked in some time and we have been having some display problems as a result. This also cuts down the display code by roughly half.

fix #1528 

fix #277
<details> 

```
(foo) pkg> status
    Status `/tmp/foo/Project.toml`
  7876af07 Example
  682c06a0 JSON

(foo) pkg> status --manifest
    Status `/tmp/foo/Manifest.toml`
    Status empty manifest

(foo) pkg> rm Example JSON
  Updating `/tmp/foo/Project.toml`
  7876af07 - Example
  682c06a0 - JSON
  Updating `/tmp/foo/Manifest.toml`
  Updating no changes

(foo) pkg> status
    Status `/tmp/foo/Project.toml`
    Status empty project

(foo) pkg> status --manifest
    Status `/tmp/foo/Manifest.toml`
    Status empty manifest
```
</details>

This also fixes an undocumented issue where you couldn't filter removed packages.
<details>

```
foo) pkg> rm Example
  Updating `/tmp/foo/Project.toml`
  7876af07 - Example v0.5.3
  Updating `/tmp/foo/Manifest.toml`
  7876af07 - Example v0.5.3

(foo) pkg> status --diff Example
      Diff `/tmp/foo/Project.toml`
  7876af07 - Example v0.5.3
```

</details>

I also changed some of the display itself, but I can change that back:

<details> 

Now:
```
(foo) pkg> add Example#master
  Updating git-repo `https://github.com/JuliaLang/Example.jl.git`
 Resolving package versions...
  Updating `/tmp/foo/Project.toml`
  7876af07 + Example v0.5.4 `https://github.com/JuliaLang/Example.jl.git#master`
  Updating `/tmp/foo/Manifest.toml`
  7876af07 + Example v0.5.4 `https://github.com/JuliaLang/Example.jl.git#master`
```

Before:
```
(foob) pkg> add Example#master
  Updating git-repo `https://github.com/JuliaLang/Example.jl.git`
 Resolving package versions...
  Updating `/tmp/foob/Project.toml`
  [7876af07] + Example v0.5.4 #master (https://github.com/JuliaLang/Example.jl.git)
  Updating `/tmp/foob/Manifest.toml`
  [7876af07] + Example v0.5.4 #master (https://github.com/JuliaLang/Example.jl.git)
```

</details>

### CODE REVIEW

**Comment by KristofferC** [comment]
Regarding

> `7876af07 + Example v0.5.4 `https://github.com/JuliaLang/Example.jl.git#master`

Previously, urls were printed with `()` and paths with `[]`.  Is there still a difference?

**Comment by 00vareladavid** [comment]
Yes, you can distinguish a dep tracking a repo because it always has a git rev.

This PR
```
     Status `/tmp/fizzle/Project.toml`
   7876af07 Example v0.5.4 `~/.julia/dev/Example`
   dcb67f36 Unregistered v0.2.0 `https://github.com/00vareladavid/Unregistered.jl#master`
```

Before
```
    Status `/tmp/previous/Project.toml`
  [7876af07] Example v0.5.4 [`~/.julia/dev/Example`]
  [dcb67f36] Unregistered v0.2.0 #master (https://github.com/00vareladavid/Unregistered.jl)
```

I think it is a lot cleaner. Thoughts?

**Comment by KristofferC** [comment]
Did this just flag out delete the indicator about packages not being downloaded?

image

I don't see this on Pkg master.

**Comment by KristofferC** [comment]
The `no changes` indicator also disappeared? e.g:

```
(@v1.4) pkg> add Example
  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
 [no changes]
   Updating `~/.julia/environments/v1.4/Manifest.toml`
 [no changes]
```

**Comment by 00vareladavid** [comment]
I did remove the `Updating` when no changes are made to the file because it is inaccurate. Perhaps some feedback like `No changes to project `~/.julia/environments/v1.4/Project.toml`' would be better?

Regarding the indicator, this PR did remove it. I'm sorry about that, it was not intentional. It was a bit difficult to keep track of all the behavior without tests. The positive side is that it should now be less likely to accidentally alter behavior because of the new tests.

**Pull request merged**
