### PR TITLE
Add a dummy commit for Julia 1.3 for General deployment

### PR DESCRIPTION
**Pull request by ararslan**
Also add 1.0.3 and change 1.1.0 to use the actual commit.

### CODE REVIEW

**Comment by ararslan** [comment]
@StefanKarpinski, there are some TOML files in here that need to be updated for this as well, right?

**Comment by ararslan** [comment]
Seems Nanosoldier is broken without this change. See https://github.com/JuliaLang/julia/commit/62d7ec55fd8063c722bc79b72c6d20b34a887c39.

**Comment by StefanKarpinski** [comment]
I cherry-picked this and pushed to master.

**Comment by ararslan** [comment]
Thanks Stefan!

**Pull request closed without merging**
