### PR TITLE
[WIP] backports release 1.4

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by KristofferC** [comment]
Maybe we should exclude "Fix that version ranges in keys for one registry also applies to vers…"? Might be better to just leave that alone for 1.4?

**Comment by fredrikekre** [comment]
Sure.

Btw, whats up with Julia master:
```
ERROR: Package Pkg errored during testing
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at /home/travis/build/JuliaLang/Pkg.jl/src/Types.jl:52
 [2] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing) at /home/travis/build/JuliaLang/Pkg.jl/src/Operations.jl:1496
 [3] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/travis/build/JuliaLang/Pkg.jl/src/API.jl:316
 [4] #test#68 at /home/travis/build/JuliaLang/Pkg.jl/src/API.jl:297 [inlined]
 [5] #test#65 at /home/travis/build/JuliaLang/Pkg.jl/src/API.jl:294 [inlined]
 [6] top-level scope at none:1
The command "julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test(; coverage=true)'" exited with 1.
```

**Comment by KristofferC** [comment]
Feels like it could have something to do with https://github.com/JuliaLang/julia/pull/35390...?

**Comment by KristofferC** [comment]
Think it needs https://github.com/JuliaLang/Pkg.jl/pull/1746. While not applicable to 1.4 Julia I think it should make the tests pass on nightly.

**Comment by fredrikekre** [comment]
Thanks.

**Pull request merged**
