### PR TITLE
Make `--outdated` tip coordinate with status mode

### PR DESCRIPTION
**Pull request by IanButterworth**
Updated: See https://github.com/JuliaLang/Pkg.jl/pull/3099#issuecomment-1146979195

### CODE REVIEW

**Comment by fredrikekre** [comment]
As a regular user, do you really care if a dependency of your dependency is outdated? I would prefer not showing any information by default in that case.

**Comment by IanButterworth** [comment]
This is the confusion this tries to solve

```

(jl_Qkbsmu) pkg> add KiteControllers
   Resolving package versions...
    Updating `/tmp/jl_Qkbsmu/Project.toml`
  [b19fd437] + KiteControllers v0.1.0
    Updating `/tmp/jl_Qkbsmu/Manifest.toml`
  [79e6a3ab] + Adapt v3.3.3
...
  [69666777] + Arrow v2.3.0
⌅ [31f734f8] + ArrowTypes v1.2.1
  [c3b6d118] + BitIntegers v0.2.6
...
⌅ [34da2185] + Compat v3.44.0
  [9a962f9c] + DataAPI v1.10.0
  [e2d170a0] + DataValueInterfaces v1.0.0
⌅ [ffbed154] + DocStringExtensions v0.8.6
  [fa6b7ba4] + DualNumbers v0.6.8
...
⌅ [90980105] + KiteUtils v0.3.5
  [929cbde3] + LLVM v4.13.0
...
        Info Packages marked with ⌅ have new versions available but cannot be upgraded. To see why use `status --outdated`

(jl_Qkbsmu) pkg> status --outdated
Status `/tmp/jl_Qkbsmu/Project.toml`

(jl_Qkbsmu) pkg> status --outdated -m
Status `/tmp/jl_Qkbsmu/Manifest.toml`
⌅ [31f734f8] ArrowTypes v1.2.1 (<v2.0.0): Arrow
⌅ [34da2185] Compat v3.44.0 (<v4.1.0): FilePathsBase, Mocking
⌅ [ffbed154] DocStringExtensions v0.8.6 (<v0.9.0): KiteUtils, LogExpFunctions, RecursiveArrayTools
⌅ [90980105] KiteUtils v0.3.5 (<v0.4.7): KiteControllers
```

The options I see:

1. Do two warnings one for the project one for the manifest each with the appropriate `--outdated` tip, with or without `-m`

2. Keep the tip as-is but `--outdated` defaults to combined (this PR)

3. `--outdated` in project mode could itself tip about `-m` mode if there are further outdated indirect deps

**Comment by KristofferC** [comment]
Make the warning consistent with how status was called? If status shown manifest pkgs, make the warning also be so that manifest pkgs are shown.

**Comment by IanButterworth** [comment]
So option 1?

**Comment by KristofferC** [comment]
I think so heh.

**Comment by IanButterworth** [comment]
Ok, updated to:

```
(Pkg) pkg> activate --temp
  Activating new project at `/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_Us4WYu`

(jl_Us4WYu) pkg> add Graphics@1.1.1
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_Us4WYu/Project.toml`
⌃ [a2bd30eb] + Graphics v1.1.1
    Updating `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_Us4WYu/Manifest.toml`
  [3da002f7] + ColorTypes v0.11.3
  [5ae59095] + Colors v0.12.8
  [53c48c17] + FixedPointNumbers v0.8.4
⌃ [a2bd30eb] + Graphics v1.1.1
⌅ [77ba4419] + NaNMath v0.3.7
  [189a3867] + Reexport v1.2.2
  [56f22d72] + Artifacts
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [e66e0078] + CompilerSupportLibraries_jll v0.5.2+0
  [4536629a] + OpenBLAS_jll v0.3.20+0
  [8e850b90] + libblastrampoline_jll v5.1.0+0
        Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ cannot be upgraded. To see why use `status --outdated -m`

(jl_Us4WYu) pkg> st
Status `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_Us4WYu/Project.toml`
⌃ [a2bd30eb] Graphics v1.1.1
Info Packages marked with ⌃ have new versions available

(jl_Us4WYu) pkg> st -m
Status `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_Us4WYu/Manifest.toml`
  [3da002f7] ColorTypes v0.11.3
  [5ae59095] Colors v0.12.8
  [53c48c17] FixedPointNumbers v0.8.4
⌃ [a2bd30eb] Graphics v1.1.1
⌅ [77ba4419] NaNMath v0.3.7
  [189a3867] Reexport v1.2.2
  [56f22d72] Artifacts
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [2f01184e] SparseArrays
  [10745b16] Statistics
  [e66e0078] CompilerSupportLibraries_jll v0.5.2+0
  [4536629a] OpenBLAS_jll v0.3.20+0
  [8e850b90] libblastrampoline_jll v5.1.0+0
Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ cannot be upgraded. To see why use `status --outdated -m`

(jl_Us4WYu) pkg> add NaNMath
   Resolving package versions...
    Updating `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_Us4WYu/Project.toml`
⌅ [77ba4419] + NaNMath v0.3.7
  No Changes to `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_Us4WYu/Manifest.toml`

(jl_Us4WYu) pkg> st
Status `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_Us4WYu/Project.toml`
⌃ [a2bd30eb] Graphics v1.1.1
⌅ [77ba4419] NaNMath v0.3.7
Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ cannot be upgraded. To see why use `status --outdated`

(jl_Us4WYu) pkg> st -m
Status `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_Us4WYu/Manifest.toml`
  [3da002f7] ColorTypes v0.11.3
  [5ae59095] Colors v0.12.8
  [53c48c17] FixedPointNumbers v0.8.4
⌃ [a2bd30eb] Graphics v1.1.1
⌅ [77ba4419] NaNMath v0.3.7
  [189a3867] Reexport v1.2.2
  [56f22d72] Artifacts
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [2f01184e] SparseArrays
  [10745b16] Statistics
  [e66e0078] CompilerSupportLibraries_jll v0.5.2+0
  [4536629a] OpenBLAS_jll v0.3.20+0
  [8e850b90] libblastrampoline_jll v5.1.0+0
Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ cannot be upgraded. To see why use `status --outdated -m`
```

**Review by KristofferC — APPROVED** [review]
Tangentially, I think we should show the hints using REPL mode or API mode depending on how the command was called. If the REPL mode was used we could store that in `Context` and then look at that field when printing suggestions. That's for another time of course.

**Pull request merged**
