### PR TITLE
silent activate when testing, fixes #1029.

### LINKED ISSUE #1029: Implementation detail about test env leaking to user
```
(v1) pkg> test Literate
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Testing Literate
[ Info: activating environment at `/tmp/tmpAP0rYi/Project.toml`.          <--- Suppress this.
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
```

### PR DESCRIPTION
**Pull request by fredrikekre**
---

#1033 became kinda big and does a lot of things. I think it is better to break it up a bit.

### CODE REVIEW

**Comment by 00vareladavid** [comment]
Don't we have to set `LOAD_PATH` as well?

**Comment by fredrikekre** [comment]
No, I thought so, but `Base.active_project` (which `EnvCache` uses) looks in `Base.ACTIVE_PROJECT` first even if that does not exist in the load path. This is a bit weird, since you can have an `active_project` but not load any packages. This might not be enough to instantiate, but lets try:

bors try

**Comment by 00vareladavid** [comment]
So it does need `LOAD_PATH`?

**Comment by fredrikekre** [comment]
> So it does need `LOAD_PATH`?

I was not able to find a case that needed it, but I feel like its a good idea to `instantate` with the same load path as the tests are run with later.

**Pull request merged**
