### PR TITLE
Update docstrings for io kwargs, some io kwarg fixes, update stdlib list

### PR DESCRIPTION
**Pull request by IanButterworth**
#2391 missed out docstrings.

Plus a few fixes

### CODE REVIEW

**Comment by IanButterworth** [comment]
Bye bye `LibOSWUnwind_jll`
Hello `LLVMLibUnwind_jll`

I also made the error log informative enough to not need to run `generate_historical_stdlibs.jl`

**Comment by IanButterworth** [comment]
@DilumAluthge I'd appreciate another set of eyes to review, perhaps beyond the diff, that all io kwargs are now updated in docstrings (the way the API is set up, it's a bit hard to track)

**Comment by DilumAluthge** [comment]
Whoops I missed this somehow. Will take a look now.

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
It's hard to be 100% sure, but I think all the docstrings are fixed now.

**Pull request merged**
