### PR TITLE
[ext/HSG]: Store next release _and_ latest nightly

### PR DESCRIPTION
**Pull request by staticfloat**
In the event that we are in an RC phase where we have three "latest"
branch tips (e.g. latest stable: 1.5.3, latest RC: 1.6.0-rc1 and latest
`master`: 1.7.0-DEV) each with their own set of standard libraries, we
must store this information in Pkg so that we pass tests when running on
latest `master`. It is harmless for this information to be baked into an
older Julia, as we make no guarantees that Julia 1.6.0 final should have
perfect information about what standard libraries 1.7.0 will have.

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2410

### CODE REVIEW

**Comment by staticfloat** [comment]
This should be merged after #2417

**Comment by DilumAluthge** [comment]
@staticfloat Can you resolve the merge conflicts?

Alternatively, since I just merged #2417 to master, it might be easier for you to just redo this commit from scratch starting with the latest master.

**Comment by staticfloat** [comment]
Yeah, it's because it bundled the commit you just merged.  Silly `git`, you should know that those two were the same commit!

**Comment by DilumAluthge** [comment]
> Yeah, it's because it bundled the commit you just merged. Silly `git`, you should know that those two were the same commit!

Classic Git.

**Comment by DilumAluthge** [comment]
> > Yeah, it's because it bundled the commit you just merged. Silly `git`, you should know that those two were the same commit!
> 
> Classic Git.

I guess this is the kind of thing that Pijul is supposed to solve.

**Pull request merged**
