### PR TITLE
Allow comment lines in REQUIRE file

### PR DESCRIPTION
**Pull request by jheinen**

### CODE REVIEW

**Comment by jheinen** [comment]
The final version should handle REQUIRE files with empty lines (as in [Plots.jl](https://github.com/JuliaPlots/Plots.jl/blob/master/REQUIRE)). This was the reason for my PR.

**Comment by timholy** [comment]
There seems to have been some merge issue. I've re-issued my PR in #1137

**Comment by StefanKarpinski** [comment]
I changed the Base of this PR because it should have been made against my PR (now merged to master) rather than Tim's PR which was orthogonal. Apparently the bors bot we use to merge PRs either ignores the base branch for PRs or it cannot handle changing the base of a PR.

**Pull request closed without merging**
