### PR TITLE
Force verbose downloads during `Pkg` operations

### PR DESCRIPTION
**Pull request by staticfloat**
This should add a progress bar (and some text about what is being downloaded) for #1554.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I'm guessing that it is too late to get this into an RC for 1.3.1, but perhaps we could backport this to 1.3.2 or something?

**Comment by KristofferC** [comment]
This seems a bit excessive maybe?

```
[ Info: No hash cache found
[ Info: Calculated hash 13fc17b97be41763b02cbb80e9d048302cec3bd3d446c2ed6e8210bddcd3ac76 for file /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_5fc40a/download_target.tar.bz2
[ Info: Unpacking /var/folders/nz/vv4_9tw56nv9k3tkvyszvw÷80000gn/T/jl_5fc40a/download_target.tar.bz2 into /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_5fc40a/target...
[ Info: Destination file /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_5fc40a/download_target.tar.bz2 already exists, verifying...
[ Info: Hash cache is consistent, returning true
[ Info: Destination directory /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_5fc40a/target already exists, returning
[ Info: Destination file /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_5fc40a/download_target.tar.bz2 already exists, verifying...
[ Info: Hash cache is consistent, returning true
[ Info: Destination directory /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_5fc40a/target already exists, returning
[ Info: Downloading https://github.com/staticfloat/small_bin/raw/f1a92f5eafbd30a0c6a8efb6947485b0f6d1bec3/socrates.tar.xz to /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_d1OMig/download_target.tar.xz...

######################################################################## 100.0%
```

Is there any way to have something similar we have for the git clones, like: 

```
Downloading artifacts:
 MKL: [=====>                           ] 40%
```

**Comment by staticfloat** [comment]
Right now, the progress bar is just being printed by `curl`.  The rest of the messages are useful when there is any possibility of corrupted state on disk, but for artifacts, it's true, it's not likely that this will happen since the tarballs are not cached.  I've threaded the `quiet_download` argument through a few more things now, so we can get just the downloading messages, which looks a lot neater.

For 1.5, I would prefer if we could instead use `HTTP.download()` and report progress through a callback function tailored to `Pkg`; We may want to modify the Artifacts API a bit to give us a list of all the things that need to be downloaded so that we can do parallel downloads or something like that as well.  Perhaps we can modify `HTTP.jl` to have a threadpool of workers, then we just run `ensure_all_artifacts_installed()` in parallel or something?

**Comment by KristofferC** [comment]
> For 1.5, I would prefer if we could instead use HTTP.download() and report progress through a callback function tailored to Pkg; 

It is still a bit unclear to me how HTTP.jl should be added to stdlib (I don't think a full source code import is that good of an idea) but getting a nice progress bar should be pretty easy then, yes.

Would it be possible to use libcurl and something like https://curl.haxx.se/libcurl/c/CURLOPT_PROGRESSFUNCTION.html (which is pretty much how we do it with LibGit2 currently). But adding new binary deps might be annoying.

> Perhaps we can modify HTTP.jl to have a threadpool of workers, then we just run ensure_all_artifacts_installed() in parallel or something?

I don't think that is needed, just create a bunch of tasks with `@async` that does the downloading (similar to how we do it downloading packages)?

**Comment by staticfloat** [comment]
> But adding new binary deps might be annoying.

Yeah, I would prefer to reduce these as much as possible.

>> Perhaps we can modify HTTP.jl to have a threadpool of workers, then we just run ensure_all_artifacts_installed() in parallel or something?

> I don't think that is needed, just create a bunch of tasks with @async that does the downloading (similar to how we do it downloading packages)?

This doesn't matter to this PR, but wouldn't that create a storm of downloads?  E.g. if you have 65 artifacts to download, you really only want ~4 of them downloading at a time, don't you?

**Comment by KristofferC** [comment]
> E.g. if you have 65 artifacts to download, you really only want ~4 of them downloading at a time, don't you?

Yeah but you do something like

```
for i in 1:4
    @async while !isempty(downloads)
        download(popfirst!(downloads))
    end
end
```

**Comment by KristofferC** [comment]
I see this in the logs now

```
[ Info: Downloading https://pkg.julialang.org/artifact/43563e7631a7eafae1f9f8d9d332e3de44ad7239 to /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_AxhclR-download.gz...

curl: (22) The requested URL returned error: 404 Not Found

[ Info: Downloading https://github.com/staticfloat/small_bin/raw/master/socrates.tar.gz to /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_Q2M9Ic-download.gz...

######################################################################## 100.0%

[ Info: Downloading https://pkg.julialang.org/artifact/43563e7631a7eafae1f9f8d9d332e3de44ad7239 to /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_AoYZcP-download.gz...

curl: (22) The requested URL returned error: 404 Not Found

[ Info: Downloading https://github.com/staticfloat/small_bin/raw/master/socrates.tar.gz to /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_1IVDcb-download.gz...

######################################################################## 100.0%

[ Info: Downloading https://pkg.julialang.org/artifact/43563e7631a7eafae1f9f8d9d332e3de44ad7239 to /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_uO6lH9-download.gz...

curl: (22) The requested URL returned error: 404 Not Found

[ Info: Downloading https://github.com/staticfloat/small_bin/raw/master/socrates.tar.gz to /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_YHRTWp-download.gz...

######################################################################## 100.0%

[ Info: Downloading https://pkg.julialang.org/artifact/43563e7631a7eafae1f9f8d9d332e3de44ad7239 to /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_0SGRRx-download.gz...

curl: (22) The requested URL returned error: 404 Not Found

[ Info: Downloading https://github.com/staticfloat/small_bin/raw/master/socrates.tar.gz to /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/jl_cMNNxK-download.gz...

######################################################################## 100.0%
```

wonder what that is about.

Anyway, this should be an improvement over the status quo but could still be improved imo.
No need to show where we download the artifact for example since it is just to a temp dir.

**Comment by KristofferC** [comment]
Is this really how the progress bar is supposed to look? Kinda trippy.

Alt Text

**Comment by staticfloat** [comment]
That means the server didn’t give you a total length, so it doesn’t know
how to present progress.

**Comment by KristofferC** [comment]
Alright, is that a problem with Pkg server?

**Comment by StefanKarpinski** [comment]
Ah, probably, we should send the total content length as a header.

**Comment by fredrikekre** [comment]
`Downloading artifacts...` is printed even though everything is downloaded already:
```
(@v1) pkg> up
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
Downloading artifacts...
   Updating `~/.julia/environments/v1/Project.toml`
 [no changes]
   Updating `~/.julia/environments/v1/Manifest.toml`
 [no changes]
```

**Comment by KristofferC** [comment]
Hm, yeah. In general, I think it is usually good to have a "collection phase" where you just gather all urls you need to download, and then a "download phase" which does the downloading. That makes it easier to check if something actually need to be downloaded (as well as concurrently do downloads as well).

**Comment by StefanKarpinski** [comment]
We should also figure out in advance the methods by which a thing should be attempted to be downloaded (Pkg protocol, GitHub release, GitHub tarball, artifact downloads, git clone). It would be good to have a phase (as Kristoffer says) where we figure out all the things to download and what methods to try for each one, and then another phase where we just do all the downloads, with a configurable throttle of how many downloads we try concurrently, regardless of method.

**Pull request merged**
