### PR TITLE
Suggest uppercased package name when not found

### PR DESCRIPTION
**Pull request by fonsp**
To help users in situations like https://github.com/fonsp/Pluto.jl/issues/1068

### CODE REVIEW

**Comment by fredrikekre** [comment]
This seems like an somewhat arbitrary thing to suggest (why not PLUTO for example)? There was a PR to Julia which suggested similar names when you try to load a package with a type (e.g. `using pluto` would suggest `using Pluto`) but I can't find it now. I think something like that would be much better.

**Comment by KristofferC** [comment]
Suggesting similar package names based on what is available in the registry would probably work better.

**Comment by fonsp** [comment]
> This seems like an somewhat arbitrary thing to suggest

Good point! Feel free to close this PR, I'm not very invested in it

**Comment by fredrikekre** [comment]
> Suggesting similar package names based on what is available in the registry would probably work better.

Yea thats what I meant.

**Comment by StefanKarpinski** [comment]
Edit distance with a low cost for case changes would be a good way to do this. Now that we have usage stats we can combine with a "language model" that uses package popularity to decide what's most likely.

**Comment by IanButterworth** [comment]
Converted into a feature request. thanks @fonsp

**Pull request closed without merging**
