### PR TITLE
sort jlls together in status printing

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]
LGTM if they are still in alphabetical order in each of the three lists.

**Comment by KristofferC** [comment]
Perhaps they should be in 

[stdlib]
[jll]
[normal]

order to show the normal ones at the bottom (where your terminal cursor is after executing the command)

**Comment by staticfloat** [comment]
LGTM, merge when ready.

**Review by staticfloat — APPROVED** [review]

**Comment by KristofferC** [comment]
Should have re-run CI here.. Should be ok though.

**Pull request merged**
