### PR TITLE
status: add icons to indicate package updatability

### PR DESCRIPTION
**Pull request by IanButterworth**
Adds two icons to the status report:
- `⌃` for packages where a newer version can be installed
- `⌅` for packages where a newer version exists, but cannot be installed

~~Also adds padding to align the version numbers to make things a bit tidier?~~

If the user wants more information they can use `pkg> status --outdated` 

I don't see a significant increase in execution time
master: `0.004629 seconds (8.33 k allocations: 722.516 KiB)`
this PR: `0.006784 seconds (8.40 k allocations: 771.539 KiB)`

Related issues
https://github.com/JuliaLang/Pkg.jl/issues/1655
https://github.com/JuliaLang/Pkg.jl/issues/2682

Todo
- [x] Needs tests adjusted for new padding etc.
- [x] Needs docs
- [x] Needs news

Edit: 
Screen Shot 2022-01-03 at 10 41 34 AM

### CODE REVIEW

**Comment by KristofferC** [comment]
I think this is an appropriate level of noise to make. Originally I thought of mimicking the icon for the "not downloaded warning" but maybe having it close to the versions, as done here, makes more sense. I wonder if having a short hint towards `status - -outdated` at the bottom when one of these are printed is a good idea. That's also similar to the not downloaded warning telling you to do an `instantiate`.

**Comment by DilumAluthge** [comment]
> I wonder if having a short hint towards `status - -outdated` at the bottom when one of these are printed is a good idea.

I think this would be a good addition!

**Comment by IanButterworth** [comment]
Added! 
I think `⌃` is obvious enough so doesn't need a hint?

```
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
  [336ed68f] CSV    v0.8.5 ⌅
  [295af30f] Revise v3.3.1
  [8dfed614] Test  
Info packages marked with ⌅ have new versions available that cannot be installed. To see why use `status --outdated`
```

**Comment by DilumAluthge** [comment]
> I think `⌃` is obvious enough so doesn't need a hint?

I was thinking we would have a hint for either symbol.

**Comment by IanButterworth** [comment]
Ok. How about this
```
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
  [336ed68f] CSV    v0.8.5 ⌃
  [295af30f] Revise v3.3.1
  [8dfed614] Test  
Info packages marked with ⌃ have new versions available
```
```
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
  [336ed68f] CSV    v0.8.5 ⌅
  [295af30f] Revise v3.3.1
  [8dfed614] Test  
Info packages marked with ⌅ have new versions available but cannot be upgraded. To see why use `status --outdated`
```
```
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
  [336ed68f] CSV    v0.8.5 ⌅
  [295af30f] Revise v3.3.0 ⌃
  [8dfed614] Test  
Info packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ cannot be upgraded. To see why use `status --outdated`
```

**Comment by DilumAluthge** [comment]
I like it!

**Comment by DilumAluthge** [comment]
Missing a colon after `Info`?

**Comment by IanButterworth** [comment]
Info is colored green, like printpkgstyle

**Comment by IanButterworth** [comment]
Is the last commit one reformat too far? It aligns the info past the version
```
     Status `/tmp/jl_BTeMGp/Project.toml`
  [54cfe95a] Pkg           v1.8.0    `~/work/Pkg.jl/Pkg.jl`
  [56f22d72] Artifacts               `@stdlib/Artifacts`
  [ade2ca70] Dates                   `@stdlib/Dates`
  [f43a241f] Downloads     v1.6.0    `@stdlib/Downloads`
  [76f85450] LibGit2                 `@stdlib/LibGit2`
  [8f399da3] Libdl                   `@stdlib/Libdl`
  [56ddb016] Logging                 `@stdlib/Logging`
  [d6f4376e] Markdown                `@stdlib/Markdown`
  [de0858da] Printf                  `@stdlib/Printf`
  [3fa0cd96] REPL                    `@stdlib/REPL`
  [9a3f8284] Random                  `@stdlib/Random`
  [ea8e919c] SHA           v0.7.0    `@stdlib/SHA`
  [9e88b42a] Serialization           `@stdlib/Serialization`
  [fa267f1f] TOML          v1.0.0    `@stdlib/TOML`
  [a4e569a6] Tar           v1.10.0   `@stdlib/Tar`
  [8dfed614] Test                    `@stdlib/Test`
  [cf7118a7] UUIDs                   `@stdlib/UUIDs`
  [3f19e933] p7zip_jll     v16.2.1+1 `@stdlib/p7zip_jll`
      Status `/tmp/jl_BTeMGp/Manifest.toml`
  [54cfe95a] Pkg                v1.8.0     `~/work/Pkg.jl/Pkg.jl`
  [0dad84c5] ArgTools           v1.1.1     `@stdlib/ArgTools`
  [56f22d72] Artifacts                     `@stdlib/Artifacts`
  [2a0f44e3] Base64                        `@stdlib/Base64`
  [ade2ca70] Dates                         `@stdlib/Dates`
  [f43a241f] Downloads          v1.6.0     `@stdlib/Downloads`
  [7b1f6079] FileWatching                  `@stdlib/FileWatching`
  [b77e0a4c] InteractiveUtils              `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL            v0.6.3     `@stdlib/LibCURL`
  [76f85450] LibGit2                       `@stdlib/LibGit2`
  [8f399da3] Libdl                         `@stdlib/Libdl`
  [56ddb016] Logging                       `@stdlib/Logging`
  [d6f4376e] Markdown                      `@stdlib/Markdown`
  [ca575930] NetworkOptions     v1.2.0     `@stdlib/NetworkOptions`
  [de0858da] Printf                        `@stdlib/Printf`
  [3fa0cd96] REPL                          `@stdlib/REPL`
  [9a3f8284] Random                        `@stdlib/Random`
  [ea8e919c] SHA                v0.7.0     `@stdlib/SHA`
  [9e88b42a] Serialization                 `@stdlib/Serialization`
  [6462fe0b] Sockets                       `@stdlib/Sockets`
  [fa267f1f] TOML               v1.0.0     `@stdlib/TOML`
  [a4e569a6] Tar                v1.10.0    `@stdlib/Tar`
  [8dfed614] Test                          `@stdlib/Test`
  [cf7118a7] UUIDs                         `@stdlib/UUIDs`
  [4ec0a83e] Unicode                       `@stdlib/Unicode`
  [deac9b47] LibCURL_jll        v7.73.0+4  `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll        v1.9.1+2   `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll        v2.24.0+2  `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll v2020.7.22 `@stdlib/MozillaCACerts_jll`
  [83775a58] Zlib_jll           v1.2.12+1  `@stdlib/Zlib_jll`
  [8e850ede] nghttp2_jll        v1.41.0+1  `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll          v16.2.1+1  `@stdlib/p7zip_jll`
```

**Comment by IanButterworth** [comment]
I'm happy with this now. 

I think the new formatting of the `status` output into columns helps with readability, but it is a little tangential.. I just noticed because the new indicators just made it a little harder to read without column formatting

**Comment by KristofferC** [comment]
Can't say I am an immediate fan of the aligning but it might be one of those things that take get used to. 

When I thought about a feature like this, I was thinking of putting the icon in the left gutter (which we already use to show the icon when a package is not downloaded).

**Comment by IanButterworth** [comment]
yeah, that's definitely viable. Without the tips I thought it needed to be beside the version number to make it clearer, but with the tips I think the gutter is a good place for it, like not downloaded tip.

I'll undo the reformatting

**Comment by IanButterworth** [comment]
Perhaps similarly to https://github.com/JuliaLang/Pkg.jl/pull/2866 in the diff mode when there are no changes we could also list packages that are held back?

```
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
  [336ed68f] CSV v0.9.11
  [c46f51b8] ProfileView v1.0.1
⌅ [295af30f] Revise v3.3.0
  [77ec8976] GTK3_jll v3.24.31+0 `~/.julia/dev/GTK3_jll`
Info packages marked with ⌅ have new versions available but cannot be upgraded. To see why use `status --outdated`

(@v1.8) pkg> up
    Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/.julia/environments/v1.8/Project.toml`
⌅ [295af30f] Revise v3.3.0
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`
⌅ [295af30f] Revise v3.3.0
Info packages marked with ⌅ have new versions available but cannot be upgraded. To see why use `status --outdated`
```

currently you'd just get
```
(@v1.8) pkg> up
    Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml
Info packages marked with ⌅ have new versions available but cannot be upgraded. To see why use `status --outdated`
```

**Comment by DilumAluthge** [comment]
Seems reasonable to me

**Comment by DilumAluthge** [comment]
Although, would that make the view for `] up` too noisy? Will users expect that `] up` only prints the packages that are modified?

**Comment by IanButterworth** [comment]
Perhaps just
```
(@v1.8) pkg> up
    Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml
Info some packages have new versions available but are held back. Use `status --outdated` for more information.
```

**Comment by DilumAluthge** [comment]
Nice!

**Comment by DilumAluthge** [comment]
Presumably it's possible to get a situation where, after you do `] up`, there are some packages that would have the `⌃` symbol, right?

E.g. if there are two optima, and the resolver has to pick one.

In that case, there would be "some packages that have new versions available", except that they aren't being held back, right? Presumably we should still print some kind of message in that case,

**Comment by DilumAluthge** [comment]
Maybe: "some packages have new versions available, but it is not possible to update to those new versions without downgrading some other packages".

**Comment by IanButterworth** [comment]
I think that's rare and `Info some packages have new versions available but are held back.` is accurate-enough for a generic message

**Comment by IanButterworth** [comment]
Added to `up` only. A no-change diff in any other `status` print won't show this info message
```
(@v1.8) pkg> up
    Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`
        Info Some packages have new versions but cannot be upgraded. To see why use `status --outdated`
```

**Comment by KristofferC** [comment]
```
(@v1.7) pkg> st
Status `~/.julia/environments/v1.7/Project.toml`
⌃ [6e4b80f9] BenchmarkTools v1.1.0
→  [f68482b8] Cthulhu v2.4.4
  [31a5f54b] Debugger v0.7.0
...
Info Packages marked with → are not downloaded, use `instantiate` to download
Info Packages marked with ⌃ have new versions available
```

looks a bit misaligned

**Comment by IanButterworth** [comment]
> Should the ⌅ have some color?

Maybe the `info` color? I didn't think it warranted green or warning or error colors.

I'll look into that alignment bug

**Comment by IanButterworth** [comment]
Screen Shot 2022-01-03 at 10 16 53 AM

**Comment by IanButterworth** [comment]
Actually both upgradable and heldback lines in the `--outdated` report are yellow.. so yellow might not make sense?

But, I think the right answer might emerge after using it? We could go with yellow and see?

**Review by KristofferC — APPROVED** [review]
Let's try with this iteration for now. Always possible to tweak based on feedback. Great job!

**Comment by DilumAluthge** [comment]
Thank you Ian!

**Pull request merged**
