### PR TITLE
put back the progress bar for downloading artifacts

### PR DESCRIPTION
**Pull request by KristofferC**
Requires https://github.com/JuliaLang/Downloads.jl/pull/35

https://asciinema.org/a/9E0hEccnYMd1YIBvazCzBwmUz

go to 00:20.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Why is the alignment broken?

**Comment by KristofferC** [comment]
Which one?

**Comment by fredrikekre** [comment]
```
  Downloading artifact ...
     Downloading ======>
```
But maybe that was intentional :)

**Comment by KristofferC** [comment]
Maybe the "Downloading" before the arrow is unnecessary. We already write Downloading above.

**Comment by fredrikekre** [comment]
Could call it `Progress: ` maybe

**Comment by KristofferC** [comment]
Wtf... why did I close this one? What happend to this PR? Did I force push something I shouldn't here?

**Pull request closed without merging**
