### PR TITLE
Add quickstart to docs

### LINKED ISSUE #689: Improvements to the Pkg docs
@mauro3 commented on [Thu May 24 2018](https://github.com/JuliaLang/julia/issues/27245)

Just reading through the new Pkg docs and I have a few suggestions:

- Title should be more descriptive, maybe as before "Packages" or "Packages (Pkg)".
- I think there should be a "Quick start" section right at the top.  Whilst the "Introduction" section is a nice long read, for someone wanting to just install a package, that is not very helpful.
- Then, whilst I understand the reason to have packages separate for each "project", for simple REPL work the old behavior of a global packages is better.  I suspect this is possible with the new Pkg, but it is not clear to me how.  I suggest to put this into the "Quick start".
- Maybe rename the "Getting started" to "Getting started with a project".

### PR DESCRIPTION
**Pull request by 00vareladavid**
Should hopefully resolve #689

### CODE REVIEW

**Comment by fredrikekre** [comment]
Great! I started on something similar last night (https://github.com/JuliaLang/Pkg.jl/tree/fe/doc-overhaul) but didn't get so far (https://github.com/JuliaLang/Pkg.jl/blob/fe/doc-overhaul/docs/src/getting-started.md).

**Comment by 00vareladavid** [comment]
Nice. I'm thinking its not a bad idea to heavily copy from [cargo's documentation](https://doc.rust-lang.org/cargo/) layout. I'm also fond of [nix's quickstart](https://nixos.org/nix/manual/#chap-quick-start).

**Comment by 00vareladavid** [comment]
Is it possible to "subtree" from Julia's docs? What I mean is to not shove everything into a single file. It seems your branch does that. I think it's a good idea.

**Comment by fredrikekre** [comment]
Yea, thats what I am doing on that branch. But that will only deploy to https://julialang.github.io/Pkg.jl/latest/. I think that is fine, and only keep something like a quick guide with reference to the "real" docs in the Julia manual.

**Comment by 00vareladavid** [comment]
That sounds perfect

**Comment by 00vareladavid** [comment]
Do you have a specific organization in mind? Again, I think I could help with certain subbranches

**Comment by 00vareladavid** [comment]
Also #615 links to a good starting point for a FAQ: https://docs.google.com/document/d/1pdfao38w8fgSnEvf1JkF4Dz2EipWJK1TmaNCUXAlRVc/edit

**Comment by fredrikekre** [comment]
> Do you have a specific organization in mind?

Not really, but this is a draft based on the current docs: https://github.com/JuliaLang/Pkg.jl/blob/066050812d9a1f362722c847d06bf563c100a1be/docs/make.jl#L10-L19

> I think cargo would be good to emulate. I could help with certain subbranches

Yea, I like the cargo docs.

**Comment by 00vareladavid** [comment]
I'm thinking roughly:

- quickstart
    - I just want access to `Plots` dammit!
- guide
    - basic commands (`add`, `rm`, `activate`, `status`, `help`)
    - recommended basic workflows (how would I do this? -> sequence of commands)
- reference (a cleaned up version of current docs)
- faq (use some things from #615 + things which come up on discourse)
    - include some less common workflows

For the guide, we could stick to using the REPL.
In the reference, it would be cool to have a mapping between REPL commands and the equivalent API expression.

**Comment by fredrikekre** [comment]
Yea, something like that. Let me clean up that branch, and then we can fill in the blanks.

**Comment by 00vareladavid** [comment]
I have a rough [guide](https://github.com/00vareladavid/Pkg.jl/tree/00/add/docs) ready. Still needs a pass for clarity/correctness/etc but I think it should be a good starting point. The essential idea is to provide a set of increasingly complex motivating examples which we can use to describe how Pkg works.

**Comment by StefanKarpinski** [comment]
It would be great to dust this off and merge it wherever is appropriate.

**Comment by fredrikekre** [comment]
I cherry-picked this commit into  #803. Thanks!

**Pull request closed without merging**
