### PR TITLE
Backports for Pkg 1.1.3

### PR DESCRIPTION
**Pull request by fredrikekre**
---
bors try

### CODE REVIEW

**Comment by 00vareladavid** [comment]
Another network error :expressionless:

**Comment by fredrikekre** [comment]
Yea, I'll just rerun it when we are closer to Julia 1.1.1.

**Comment by fredrikekre** [comment]
bors try

**Comment by fredrikekre** [comment]
bors try

**Comment by KristofferC** [comment]
Maybe merge this and put it onto https://github.com/JuliaLang/julia/pull/31039?

**Pull request merged**
