### PR TITLE
minor code quality improvements on `LazilyInitializedFields`

### PR DESCRIPTION
**Pull request by aviatesk**
- use `isexpr` to tidy up branch conditions
- remove unnecessary `@pure` annotation
- add type annotation on `in_lazy_struct`

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Could you also upstream these improvements to https://github.com/KristofferC/LazilyInitializedFields.jl?

**Comment by aviatesk** [comment]
https://github.com/KristofferC/LazilyInitializedFields.jl/pull/28

**Comment by aviatesk** [comment]
@DilumAluthge @KristofferC Can we get this commit into Julia master? This is required for #48682 to be completed.

**Comment by DilumAluthge** [comment]
Yeah.

**Comment by aviatesk** [comment]
Thanks.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/julia/pull/48690

**Pull request merged**
