### PR TITLE
Precompilation workload: set `"JULIA_PKG_UNPACK_REGISTRY" => nothing`

### LINKED ISSUE #3663: Pkg's precompilation workload errors if you do some shenanigans with the depot path and some Pkg-related environment variables
I figure it would be useful to actually write up the MWE somewhere.

## MWE

First, get a recent Julia nightly. Here's the one I used:

```
Version 1.11.0-DEV.657 (2023-10-16)
Commit 258ac4614f5 (0 days old master)
```

Second, start a REPL with the aforementioned Julia nightly and run the following Julia script:

```julia
env2 = copy(ENV);
delete!(env2, "JULIA_LOAD_PATH");
env2["JULIA_DEPOT_PATH"] = mktempdir()
# env2["JULIA_DEBUG"] = "loading"
env2["JULIA_PKG_SERVER"] = ""
env2["JULIA_PKG_UNPACK_REGISTRY"] = "true"

julia_binary = Base.julia_cmd()[1]

cmd = `$(julia_binary) -e 'import Pkg; @info "Hello world"'`

run(setenv(cmd, env2));
```

We expect this to take a minute or two, because it needs to precompile Pkg.

## Expected output

After a minute or two, it should print "Hello world", and it should not print any errors.

## Actual output"

After a minute or two, it errors with the following error message:

```
ERROR: LoadError: The following package names could not be resolved:
 * TestPkg (not found in project, manifest or registry)
   Suggestions: IsoPkg TestEnv TestImages
```

<details>

<summary>Here is the full stacktrace: (click to expand)</summary>

```
julia> run(setenv(cmd, env2))
ERROR: LoadError: The following package names could not be resolved:
 * TestPkg (not found in project, manifest or registry)
   Suggestions: IsoPkg TestEnv TestImages
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/Types.jl:70
  [2] ensure_resolved(ctx::Pkg.Types.Context, manifest::Pkg.Types.Manifest, pkgs::Vector{Pkg.Types.PackageSpec}; registry::Bool)
    @ Pkg.Types ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/Types.jl:1030
  [3] ensure_resolved
    @ Pkg.Types ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/Types.jl:981 [inlined]
  [4] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::@Kwargs{io::Pkg.UnstableIO})
    @ Pkg.API ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/API.jl:267
  [5] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Pkg.UnstableIO, kwargs::@Kwargs{})
    @ Pkg.API ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/API.jl:159
  [6] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/API.jl:148
  [7] add
    @ Pkg.API ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/API.jl:147 [inlined]
  [8] add
    @ Pkg.API ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/API.jl:146 [inlined]
  [9] (::Pkg.var"#9#14")()
    @ Pkg ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/precompile.jl:86
 [10] withenv(f::Pkg.var"#9#14", keyvals::Pair{String, Int64})
    @ Base ./env.jl:239
 [11] (::Pkg.var"#8#13"{Pkg.var"#_run_precompilation_script_setup#10"})()
    @ Pkg ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/precompile.jl:85
 [12] withenv(f::Pkg.var"#8#13"{Pkg.var"#_run_precompilation_script_setup#10"}, keyvals::Pair{String, Nothing})
    @ Base ./env.jl:239
 [13] (::Pkg.var"#pkg_precompile#12"{Pkg.var"#_run_precompilation_script_setup#10"})()
    @ Pkg ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/precompile.jl:83
 [14] top-level scope
    @ ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/precompile.jl:111
 [15] include(mod::Module, _path::String)
    @ Base ./Base.jl:497
 [16] include(x::String)
    @ Pkg ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/Pkg.jl:3
 [17] top-level scope
    @ ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/Pkg.jl:821
 [18] include
    @ Base ./Base.jl:497 [inlined]
 [19] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2302
 [20] top-level scope
    @ stdin:3
in expression starting at /Users/dilum/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/precompile.jl:6
in expression starting at /Users/dilum/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/Pkg/src/Pkg.jl:3
in expression starting at stdin:3
ERROR: Failed to precompile Pkg [44cfe95a-1eb2-52ea-b672-e2afdf69b78f] to "/var/folders/yf/1bpklfv955vdhc4fmvll26c40000gp/T/jl_ZYZb91/compiled/v1.11/Pkg/jl_Vzpg0U".
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:2554
  [3] compilecache
    @ Base ./loading.jl:2420 [inlined]
  [4] (::Base.var"#1002#1003"{Base.PkgId})()
    @ Base ./loading.jl:2022
  [5] mkpidlock(f::Base.var"#1002#1003"{Base.PkgId}, at::String, pid::Int32; kwopts::@Kwargs{stale_age::Int64, wait::Bool})
    @ FileWatching.Pidfile ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:93
  [6] #mkpidlock#6
    @ FileWatching.Pidfile ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:88 [inlined]
  [7] trymkpidlock(::Function, ::Vararg{Any}; kwargs::@Kwargs{stale_age::Int64})
    @ FileWatching.Pidfile ~/.asdf/installs/julia/nightly/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:111
  [8] #invokelatest#2
    @ Base ./essentials.jl:901 [inlined]
  [9] invokelatest
    @ Base ./essentials.jl:896 [inlined]
 [10] maybe_cachefile_lock(f::Base.var"#1002#1003"{Base.PkgId}, pkg::Base.PkgId, srcpath::String; stale_age::Int64)
    @ Base ./loading.jl:3066
 [11] maybe_cachefile_lock
    @ Base ./loading.jl:3063 [inlined]
 [12] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:2018
 [13] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1863
 [14] #invoke_in_world#3
    @ Base ./essentials.jl:933 [inlined]
 [15] invoke_in_world
    @ Base ./essentials.jl:930 [inlined]
 [16] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1854
 [17] macro expansion
    @ Base ./loading.jl:1792 [inlined]
 [18] macro expansion
    @ Base ./lock.jl:267 [inlined]
 [19] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1754
 [20] #invoke_in_world#3
    @ Base ./essentials.jl:933 [inlined]
 [21] invoke_in_world
    @ Base ./essentials.jl:930 [inlined]
 [22] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1747
ERROR: failed process: Process(setenv(`/Users/dilum/.asdf/installs/julia/nightly/bin/julia -e 'import Pkg; @info "Hello world"'`,["XPC_FLAGS=0x0", "PATH=/Users/dilum/.asdf/installs/julia/nightly/bin:/Users/dilum/.asdf/shims:/Users/dilum/.asdf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin", "COMMAND_MODE=unix2003", "PWD=/Users/dilum/Downloads", "ASDF_CONFIG_FILE=/Users/dilum/.asdfrc", "XPC_SERVICE_NAME=0", "TERM_PROGRAM=iTerm.app", "ASDF_DATA_DIR=/Users/dilum/.asdf", "JULIA_PKG_UNPACK_REGISTRY=true", "SHELL=/bin/bash"  …  "BASH_SILENCE_DEPRECATION_WARNING=1", "USER=dilum", "ITERM_SESSION_ID=w0t0p0:F5EDF1A0-5D35-49EC-9A14-B877C3EC0E82", "ASDF_DIR=/Users/dilum/.asdf", "HOME=/Users/dilum", "TERM=xterm-256color", "TERM_PROGRAM_VERSION=3.4.21", "OPENBLAS_MAIN_FREE=1", "COLORTERM=truecolor", "JULIA_DEPOT_PATH=/var/folders/yf/1bpklfv955vdhc4fmvll26c40000gp/T/jl_ZYZb91"]), ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error
   @ Base ./process.jl:565 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:480
 [3] run(::Cmd)
   @ Base ./process.jl:477
 [4] top-level scope
   @ REPL[8]:1
```

</details>

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #3663

### CODE REVIEW

**Comment by KristofferC** [comment]
Why does `JULIA_PKG_UNPACK_REGISTRY` have anything to do with a modified `DEPOT_PATH`?

**Comment by DilumAluthge** [comment]
If you don't modify the depot path, there's no need to precompile Pkg (because you can use the existing cache files), so the precompilation workload never gets run.

If you do modify the depot path, Pkg needs to be precompiled, so the precompilation workload gets run. If the "unpack registries" environment variable is set, this clashes with the "setup" function inside the precompilation workflow, which specifically sets up a non-unpacked registry.

**Comment by KristofferC** [comment]
To me, it seems like we should just set some kind of default `DEPOT_PATH` when running the precompile workload? Otherwise, you won't precompile the whole unpack part, no?

**Comment by DilumAluthge** [comment]
> To me, it seems like we should just set some kind of default `DEPOT_PATH` when running the precompile workload

I think we already do that:

https://github.com/JuliaLang/Pkg.jl/blob/ee39026b85e108612782df35d8acb2144c522c5b/src/precompile.jl#L10-L11

**Comment by DilumAluthge** [comment]
> Otherwise, you won't precompile the whole unpack part, no?

Which code path are you talking about precompiling? The default code path (the user doesn't set the `JULIA_PKG_UNPACK_REGISTRY` environment variable), or the code path I'm hitting (the user has set the `JULIA_PKG_UNPACK_REGISTRY` environment variable to `true`)?

**Pull request merged**
