### PR TITLE
fix not hardcoding "Project.toml" when fixing up extensions in manifest

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3815

### CODE REVIEW

**Comment by KristofferC** [comment]
CI error in windows seems relevant...

```
  SystemError: longpath: The system cannot find the path specified. 
  Stacktrace:
    [1] windowserror(p::Symbol, code::UInt32; extrainfo::Nothing)
      @ Base .\error.jl:191
    [2] windowserror
      @ .\error.jl:190 [inlined]
    [3] longpath(path::String)
      @ Base.Filesystem .\path.jl:479
    [4] isfile_casesensitive(path::String)
      @ Base .\loading.jl:15
    [5] locate_project_file
      @ .\loading.jl:582 [inlined]
``

**Comment by kimikage** [comment]
xref: https://github.com/JuliaLang/julia/issues/54799

**Comment by IanButterworth** [comment]
The fix is https://github.com/JuliaLang/julia/pull/55220

**Comment by KristofferC** [comment]
Can we fix it on this side as well by calling `abspath`?

**Review by IanButterworth — APPROVED** [review]

**Pull request merged**
