### PR TITLE
Add support for a `git` interface in the REPL

### PR DESCRIPTION
**Pull request by 00vareladavid**
#620 seems like a neat idea. I think it makes sense to access `git` directly since Pkg relies on `git` so heavily.

### CODE REVIEW

**Comment by KristofferC** [comment]
I think this is a bit of a feature creep. Shell mode with `git` should work well enough imo.

**Comment by 00vareladavid** [comment]
The main issue with shell mode is that it does not automatically track the active environment. A user has to keep adjusting the current working directory in order for git to operate on the correct project. This is annoying when developing interactively.

I agree that it would be a feature creep for the API, but this is purely for interactive usage. This comes down to a judgement of how friendly the Pkg REPL should be.

**Comment by 00vareladavid** [comment]
FWIW I'm not completely sold on this idea yet. But it's nice to have an implementation to get a feel for how this affects your workflow :grin:

**Comment by 00vareladavid** [comment]
:thinking: What about a pkg-shell mode? Hitting some key would switch you to regular shell-mode, except that we wrap in a `cd(dirname(Base.active_project()))`? I think this would prevent any kind of scope creep since we just offload the work to shell-mode (or whatever its called..) and it would retain a big improvement in interactive usage

**Comment by 00vareladavid** [comment]
Upon more reflection, you guys are probably right. There are more pressing issues to deal with anyway

**Pull request closed without merging**
