### PR TITLE
Remove a case of type piracy

### LINKED ISSUE #282: Pkg3 is a pirate
```
WARNING: Method definition isless(Base.UUID, Base.UUID) in module Types at /Users/kristoffer/julia/usr/share/julia/stdlib/v0.7/Pkg3/src/Types.jl:32 overwritten in module Types at /Users/kristoffer/.julia/dev/Pkg3/src/Types.jl:32.
WARNING: Method definition in(Base.VersionNumber, Base.VersionNumber) in module Types at /Users/kristoffer/julia/usr/share/julia/stdlib/v0.7/Pkg3/src/Types.jl:196 overwritten in module Types at /Users/kristoffer/.julia/dev/Pkg3/src/Types.jl:196.
```

### PR DESCRIPTION
**Pull request by ararslan**
Repurposed to fix #282.

### CODE REVIEW

**Comment by ararslan** [comment]
bors try

**Comment by ararslan** [comment]
I was wrong, it was being used somehow, subtly.

**Comment by ararslan** [comment]
bors try

**Comment by ararslan** [comment]
Okay, up to you. I have a fix for another case of type piracy for which I can repurpose this PR.

**Comment by 00vareladavid** [comment]
Cool, I'll merge the other one

**Comment by ararslan** [comment]
bors try

**Comment by fredrikekre** [comment]
If you wanna fix #282 you can remove the `isless` method too.

**Comment by ararslan** [comment]
I can wrap that definition in a version check once https://github.com/JuliaLang/julia/pull/30947 is merged.

**Comment by ararslan** [comment]
Version check added.

bors try

**Comment by ararslan** [comment]
Good to merge?

**Pull request merged**
