### PR TITLE
Tweak wording to make "no changes" message more accurate

### PR DESCRIPTION
**Pull request by ericphanson**
fixes https://github.com/JuliaLang/Pkg.jl/issues/3066

(cc @haberdashPI)

edit: I'll need to update the tests

### CODE REVIEW

**Comment by IanButterworth** [comment]
> No packages added to or removed from ..

Changes could be a lot more things than just added or removed i.e. version changes, path changes, pin status etc.

I had proposed

> No changes to the dependencies in /path/to/Manifest.toml but metadata was updated

If we don't want to mention the metadata part because it's hard to track and know whether it's changed could just say 

> No changes to the dependencies in /path/to/Manifest.toml

**Comment by haberdashPI** [comment]
> No changes to the dependencies in /path/to/Manifest.toml

This is quite misleading as a user with no deep knowledge of Pkg internals (and the metadata part only adds a bit to my confusion). I think it has the same problems as the extant message. 

I think the main problem with the current wording is that as a user "change" can be understood to mean any change to the file on disk regarding a dependency. But e.g. `resolve` might change whether a dev'ed package can be compiled successfully, which clearly means there was a change to one of the dependencies in Manifest.toml (right??), even though this message will show up in that case.

What about:

> No dependencies needed to be installed or uninstalled due to changes in Project.toml/Manifest.toml

This makes it clear that there were indeed changes to the toml files.

**Comment by ericphanson** [comment]
> Changes could be a lot more things than just added or removed i.e. version changes, path changes, pin status etc.

So this message prints when `all(p-> p[2] == p[3], xs)` holds, which is some statement about the difference in env caches. I think you are saying roughly: "if there is no difference in env caches, we know more than no packages were added or removed! we also know you didn't pin something, or change a version, or change a path!" And therefore the message should reflect this stronger notion of lack of change.

My counter is: the current message is basically wrong (there are, in fact, changes to the manifest/project in many cases). The new message I propose here is actually 100% correct, it is just not as strong as it possibly could be; we could be making even bigger claims about not only packages not changing but also pin status not changing etc.

So the question is, how much does making bigger claims here help the user? Well, Pkg helpfully prints most changes/updates/etc, so this message is mostly in lieu of printing *nothing*, so the user knows the command actually ran. So what we need to tell the user is: "we ran your command and there's nothing worth reporting about specifically". I don't think that needs the strongest possible wording. I think that just shouldn't *overstate* the case.

Therefore, in my opinion, the current simple wording I propose is an improvement over the status quo (saying false things -> saying true things), and that a more nuanced printing about exactly how little has changed isn't super useful.

**Comment by haberdashPI** [comment]
I'm good with your wording @ericphanson, but I could also imagine:

> No dependencies were installed or uninstalled

**Comment by ericphanson** [comment]
Take another look @IanButterworth ? Seems like this bothers others too, #4031

**Comment by IanButterworth** [comment]
Seems well reasoned and worth giving a go

**Pull request merged**
