### PR TITLE
WIP: add package converter (creating Project.toml from REQUIRE)

### PR DESCRIPTION
**Pull request by KristofferC**
As an example:

```
julia> Pkg.create_project("DataFrames")
[ Info: Registered package, using already given UUID: a93c6f00-e57d-5684-b7b6-d8193f3e46c0
[ Info: Added Project.toml to /Users/kristoffer/.julia/dev/DataFrames

shell> cat DataFrames/Project.toml
name = "DataFrames"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "0.11.6"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStreams = "9a8bc11e-79be-5b39-94d7-1ccc349a1a85"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SortingAlgorithms = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[compat]
CategoricalArrays = "0.3.5"
CodecZlib = "0.4.0"
Compat = "0.59.0"
DataStreams = "0.3.0"
Missings = "0.2.3"
StatsBase = "0.11.0"
WeakRefStrings = "0.4.0"

[targets.test.deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
```

The tricky thing is what to set the `compat` section to. The problem is that packages do not agree on what the minor version is used for pre 1.0. Many packages sees bumping the minor version as breaking but other do not.

So in this example `Compat = "0.59.0"` would give the range `[0.59.0, 0.60.0)` which would exclude a bunch of the recent Compat versions which is wrong.
We could introduce a notation that is something like `>= 0.3.5` to indicate [0.3.5, inf)` which would be the most accurate conversion of the existing bound in REQUIRE but we do want people to use the semver version since that would be more proper...

Thoughts?

### CODE REVIEW

**Comment by staticfloat** [comment]
In [`DataFrames.jl`'s REQUIRE file](https://github.com/libgit2/libgit2/pull/4678/files), it only lists `Compat 0.59.0`, which means `[0.59.0, Inf)`, right?  If I actually wanted an upper bound, I would specify that within the `REQUIRE` file, so I think in that sense it doesn't really matter how people are using the semvers.

**Comment by KristofferC** [comment]
Ok, now when we have inequality specifiers, this prints:

```
name = "DataFrames"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "0.11.6"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStreams = "9a8bc11e-79be-5b39-94d7-1ccc349a1a85"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SortingAlgorithms = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[compat]
CategoricalArrays = ">=0.3.5"
CodecZlib = ">=0.4.0, <0.7.0"
Compat = ">=0.59.0"
DataStreams = ">=0.3.0"
LaTeXStrings = ">=0.2.0, <0.4.0"
Missings = ">=0.2.3"
StatsBase = ">=0.11.0"
WeakRefStrings = ">=0.4.0"

[targets.test.deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
```

**Comment by StefanKarpinski** [comment]
Should we get fancy and allow/use Unicode `≥` and `≤` for this? It looks much nicer 😁

**Comment by quinnj** [comment]
My terminal and editor have ligatures, so I get that automatically!

**Comment by KristofferC** [comment]
Sure, we can support that.

**Comment by Nosferican** [comment]
Shouldn't that spit `[extras]`, `[targets]`?

**Comment by KristofferC** [comment]
It does in https://github.com/JuliaLang/PkgDev.jl/pull/144, closing in favour.

**Pull request closed without merging**
