### PR TITLE
Use permutedims instead of LinearAlgebra.transpose (via Base), fix #896.

### LINKED ISSUE #896: Pkg requires LinearAlgebra implicitly via Base.transpose
From using `Pkg` without loading `LinearAlgebra`:
```
ERROR: MethodError: no method matching transpose(::BitArray{2})
```

### PR DESCRIPTION
**Pull request by fredrikekre**
bors try

### CODE REVIEW

**Comment by KristofferC** [comment]
Would be good with just a simple benchmark here e.g. `@time add Plots` a few times.

**Comment by fredrikekre** [comment]
I timed `Pkg.add("Plots")` without needing to download anything (which should put as much relative time as possible in e.g. resolve) and there are no difference:

**master**
```
  0.121418 seconds
  0.103115 seconds
  0.132629 seconds
  0.102283 seconds
```
**PR**
```
  0.122515 seconds
  0.109008 seconds
  0.111462 seconds
  0.141039 seconds
```

and compare to a situation where we also need to download this is even less of a problem.

**Comment by fredrikekre** [comment]
If this becomes a real problem we should move the optimized `transpose(::BitArray)` to `permutedims` and have `transpose` call that.
bors r+

**Pull request merged**
