### PR TITLE
Backports for 1.1.2

### PR DESCRIPTION
**Pull request by fredrikekre**
bors try

### CODE REVIEW

**Comment by 00vareladavid** [comment]
For future reference, how would this be pushed upstream? On this side we just bump the version in `Project.toml` and tag it using the GitHub AP, correct?

**Comment by fredrikekre** [comment]
Yea, tag a release and bump the commit in JuliaLang/julia like https://github.com/JuliaLang/julia/pull/30521

**Comment by 00vareladavid** [comment]
Ok, thanks for explaining. I appreciate it.

One more question: how do you determine the checksums?

**Pull request merged**
