### PR TITLE
Don't put recursive dependencies in the test/build project, fixes #1144.

### LINKED ISSUE #1144: Test deps not required on nightly
e.g. https://travis-ci.org/JuliaGraphs/LightGraphs.jl/builds/519328333

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
The test case added in #1058 actually demonstrates that it was broken since `JSON` should not be in the project there at all :)

bors try

**Comment by fredrikekre** [comment]
bors try

**Comment by KristofferC** [comment]
Ouch. Thanks for cleaning up my mess here.

**Pull request merged**
