### PR TITLE
Revert "release1.7: Revert "Enable installation of versioned historical stdlibs (#2614)""

### PR DESCRIPTION
**Pull request by KristofferC**
Reverts JuliaLang/Pkg.jl#2635

### CODE REVIEW

**Comment by KristofferC** [comment]
All these forced CI checks are very annoying....

**Comment by DilumAluthge** [comment]
Want to just change it to only require the "docs" check?

The main purpose is to prevent accidentally committing directly to master, and we only need to require a single check for that to work.

**Comment by DilumAluthge** [comment]
> Want to just change it to only require the "docs" check?

I've done this.

**Comment by KristofferC** [comment]
Yeah, docs is fast enough I think.

**Pull request merged**
