### PR TITLE
Deprecate `Pkg.generate`

### PR DESCRIPTION
**Pull request by DilumAluthge**
cc: @StefanKarpinski

### CODE REVIEW

**Comment by KristofferC** [comment]
It's used everywhere in the tests so cannot do it exactly like this.

**Comment by StefanKarpinski** [comment]
How about just having the deprecation warning in the command-line interface? I feel a lot less bad about breaking interactive stuff like that. That way the tests don't have to change and any scripted usage of this keeps working.

**Comment by DilumAluthge** [comment]
Sure. How do you do a depwarn for the REPL mode only?

**Comment by DilumAluthge** [comment]
Alright, here is a PR to deprecate only the REPL mode: https://github.com/JuliaLang/Pkg.jl/pull/1923

**Comment by DilumAluthge** [comment]
Closing in favor of #1923

**Pull request closed without merging**
