### PR TITLE
GitHub actions

### LINKED ISSUE #2066: Proposal: move all CI to GitHub Actions CI
Currently the Linux and Mac tests run on Travis, and the Windows tests run on AppVeyor.

Would it more convenient to have all of CI on a single provider?

Options include:
1. ~~Put everything in Travis CI~~ not an option, as Travis on Windows is too slow
2. Put everything in GitHub Actions CI

### PR DESCRIPTION
**Pull request by KristofferC**
Closes #2166
Fixes #2066

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Seems to be working now.

**Comment by KristofferC** [comment]
Yeah, in the original PR:

> There appears to be some odd TEMP dir issues on windows:

If that happens here, I'll just disable Windows and we keep AV for win.

**Comment by DilumAluthge** [comment]
Can you add these lines to the PR description?
- Closes #2166 
- Fixes #2066

**Comment by DilumAluthge** [comment]
Looks like Windows is struggling on GHA. So let's keep AV for now?

**Comment by KristofferC** [comment]
I removed Windows as well as removing testing with Pkg server for now because the Pkg server is completely broken. We can enable it when it works again.

**Comment by DilumAluthge** [comment]
It might be more readable to list these items as below. Also, it makes it easier to comment/uncomment items selectively:

```yaml
os:
- ubuntu-latest
- macOS-latest
- windows-latest
```

```yaml
pkg-server:
  - 'pkg.julialang.org'
  - ''
```

**Pull request merged**
