### PR TITLE
[release-1.6] On Julia 1.6, print a better error message instead of the `AssertionError: sourcepath !== nothing`

### PR DESCRIPTION
**Pull request by DilumAluthge**
Please note: the base (target) branch of this PR is the `release-1.6` branch.

---

This PR fixes the issue described in https://discourse.julialang.org/t/strange-error-for-unsupported-julia-version/74489 by replacing the old error message (`ERROR: AssertionError: sourcepath !== nothing`) with a new, more informative error message:
> ERROR: This manifest file was generated by a different version of Julia and thus is not compatible with this version of Julia. To generate a manifest file that is compatible with this version of Julia, run `import Pkg; Pkg.resolve()`. Please note, however, that this will re-resolve the package versions in the environment.

### CODE REVIEW

**Comment by IanButterworth** [comment]
I think we might want to do https://github.com/JuliaLang/Pkg.jl/pull/2666 instead? That saves fnding all the places an error might pop up by warning the user upfront.

It got left behind, partially because we hadn't seen many reports like this.. but it seems good to get it into 1.6

Do you have a reproducer? If so, would you mind testing that PR and commenting there?

**Comment by DilumAluthge** [comment]
I do have a reproducer, but not for Julia 1.6. I have a reproducer for Julia 1.5.

Here's a reproducer for Julia 1.5:

```julia
import Pkg

project_dir = mktempdir(; cleanup = true)
project_file = joinpath(project_dir, "Project.toml")
manifest_file = joinpath(project_dir, "Manifest.toml")
open(project_file, "w") do io
    println(io, "[deps]")
    println(io, "NetworkOptions = \"ca575930-c2e3-43a9-ace4-1e988b2c1908\"")
end
open(manifest_file, "w") do io
    println(io, "[[NetworkOptions]]")
    println(io, "uuid = \"ca575930-c2e3-43a9-ace4-1e988b2c1908\"")
    println(io, "version = \"1.2.0\"")
end

Pkg.activate(project_dir)
Pkg.instantiate()
```

If you run that script on Julia master, it runs without any errors. (It does print the "old manifest format" warning, but it instantiates without any errors.)

But if you run that script on Julia 1.5.4, the instantiate step will throw the `ERROR: AssertionError: sourcepath !== nothing` error.

**Comment by DilumAluthge** [comment]
Let me try that reproducer out against #2666 and see if the warning correctly appears.

**Comment by DilumAluthge** [comment]
I ran that reproducer on Julia 1.6.5 with PR #2666, but I got no warnings:

```
dilum@localhost:~/Downloads/Pkg.jl$ julia --project
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.5 (2021-12-19)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> Base.ACTIVE_PROJECT[]
"/Users/dilum/Downloads/Pkg.jl/Project.toml"

julia> import Pkg

julia> project_dir = mktempdir(; cleanup = true)
"/var/folders/jy/7hh5zyw95cg2lh66lfpthqq80000gn/T/jl_6gRTAa"

julia> project_file = joinpath(project_dir, "Project.toml")
"/var/folders/jy/7hh5zyw95cg2lh66lfpthqq80000gn/T/jl_6gRTAa/Project.toml"

julia> manifest_file = joinpath(project_dir, "Manifest.toml")
"/var/folders/jy/7hh5zyw95cg2lh66lfpthqq80000gn/T/jl_6gRTAa/Manifest.toml"

julia> open(project_file, "w") do io
           println(io, "[deps]")
           println(io, "NetworkOptions = \"ca575930-c2e3-43a9-ace4-1e988b2c1908\"")
       end

julia> open(manifest_file, "w") do io
           println(io, "[[NetworkOptions]]")
           println(io, "uuid = \"ca575930-c2e3-43a9-ace4-1e988b2c1908\"")
           println(io, "version = \"1.2.0\"")
       end

julia> Base.ACTIVE_PROJECT[]
"/Users/dilum/Downloads/Pkg.jl/Project.toml"

julia> read(joinpath(project_dir, "Project.toml"), String) |> println
[deps]
NetworkOptions = "ca575930-c2e3-43a9-ace4-1e988b2c1908"


julia> read(joinpath(project_dir, "Manifest.toml"), String) |> println
[[NetworkOptions]]
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
version = "1.2.0"


julia> Pkg.activate(project_dir)
  Activating environment at `/var/folders/jy/7hh5zyw95cg2lh66lfpthqq80000gn/T/jl_6gRTAa/Project.toml`

julia> Pkg.instantiate()

julia>
```

**Comment by DilumAluthge** [comment]
That being said, I do still think we should merge #2666.

**Comment by IanButterworth** [comment]
There's a reproducer manifest here https://github.com/JuliaLang/Pkg.jl/pull/2666#issuecomment-1014816506

**Comment by IanButterworth** [comment]
#2666 is merged now. I think that might suffice? Feel free to reopen if not

**Pull request closed without merging**
