### PR TITLE
only auto update registries on `add` once per day

### PR DESCRIPTION
**Pull request by KristofferC**
I think it is fine to only do the auto registry update on `Pkg.add` ~ once per day.

### CODE REVIEW

**Review by IanButterworth — APPROVED** [review]

**Comment by IanButterworth** [comment]
I tried this out and somehow `registry_update_log[string(reg.uuid)] = now()` isn't getting set for me in `Registry.update` meaning the dict is always empty on write.

**Comment by IanButterworth** [comment]
Also, it seems popular to just remove auto registry update from `add`, but perhaps add a message if the registry is older than a certain period, say 1 week??

**Comment by KristofferC** [comment]
> I tried this out and somehow registry_update_log[string(reg.uuid)] = now() isn't getting set for me in Registry.update meaning the dict is always empty on write.

Hm, I tried this and it seemed to write for me. Can you check where the code is going that doesn't hit the dict setting code?

**Comment by IanButterworth** [comment]
Unfortunately it's working for me now. I also can't see a gap in the code.

For the record I have General via packed tarball and two other git registries

**Comment by fonsp** [comment]
This is great!  🎉

Perhaps this could also replace `Pkg.UPDATED_REGISTRY_THIS_SESSION`? It seems like `UPDATED_REGISTRY_THIS_SESSION` used to be a heuristic for "has been updated recently", which is now implemented directly. Or is there a specific reason to track that it has been updated within the current session?

**Comment by IanButterworth** [comment]
Yeah people that were setting `Pkg. UPDATED_REGISTRY_THIS_SESSION = true` should be able to remove that if they're only using julia versions that have this. Though, this is less heavy-handed. It still allows `up` to update the registry once a day.

**Comment by IanButterworth** [comment]
@KristofferC and I discussed offline and agreed this is good to go

**Pull request merged**
