### PR TITLE
1.6.1 backports

### PR DESCRIPTION
**Pull request by IanButterworth**
## PRs with backport label
- [x] If user does e.g. Pkg.add("Foo.jl"), instruct them to do Pkg.add("Foo") instead https://github.com/JuliaLang/Pkg.jl/pull/2099
- [x] Avoid invalidations related to * string concat https://github.com/JuliaLang/Pkg.jl/pull/2325 
- [x] Make downloads respect IO https://github.com/JuliaLang/Pkg.jl/pull/2391 
- [x] Precompile: Remember packages that need precompilation to catch stale dependents https://github.com/JuliaLang/Pkg.jl/pull/2373 
- [x] Precomp: safer recall_precompile_state https://github.com/JuliaLang/Pkg.jl/pull/2426 
- [x] make progressbar adapt to size of terminal https://github.com/JuliaLang/Pkg.jl/pull/2437
- [x] Precompilation: Tidy report at end https://github.com/JuliaLang/Pkg.jl/pull/2457
- [x] Do not unnecessarily remove entries from compat https://github.com/JuliaLang/Pkg.jl/pull/2450
- [x] Precompilation: add tip to auto-precomp for getting error details https://github.com/JuliaLang/Pkg.jl/pull/2462

Manual cherry-picks
- [x] If the JULIA_PKG_SERVER environment variable is not set, use Git for cloning registries https://github.com/JuliaLang/Pkg.jl/pull/2377
    Required a change of approach. See https://github.com/IanButterworth/Pkg.jl/blob/cdf685a6a1f40607df185cbacec8a1db5cec4a7b/src/Types.jl#L1003-L1004
- [x] Fix status output for pin/free https://github.com/JuliaLang/Pkg.jl/pull/2446
- [x] Update docstrings for io kwargs, some io kwarg fixes, (removed: update stdlib list) https://github.com/JuliaLang/Pkg.jl/pull/2402

## Individual commit backports
- [x] Fix a typo in progress bar https://github.com/JuliaLang/Pkg.jl/commit/8b0045daf928e55e06a4701d959caba2487bd63f
- [x] fix STDLIBS_BY_VERSION on non-latest version of Julia https://github.com/JuliaLang/Pkg.jl/pull/2425/commits/ed19f829589d8a4d199adc084d8d5b83bf6f536a

### CODE REVIEW

**Comment by IanButterworth** [comment]
I'm seeing some errors locally that aren't covered by tests. Investigating

**Comment by IanButterworth** [comment]
The error I see locally is odd.. they're the same type. the only difference is one was deserialized.

The location the cache is saved to is already environment & `VERSION` specific

https://github.com/JuliaLang/Pkg.jl/blob/7a9d96545a9c30009b6653374a0ee960383441b6/src/API.jl#L1319

```julia
(@v1.7) pkg> precompile
ERROR: MethodError: Cannot `convert` an object of type Pkg.Types.PackageSpec to an object of type Pkg.Types.PackageSpec
Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:225
  Pkg.Types.PackageSpec(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at /Users/ian/Documents/GitHub/Pkg.jl/src/Types.jl:80
Stacktrace:
  [1] setindex!(A::Vector{Pkg.Types.PackageSpec}, x::Pkg.Types.PackageSpec, i1::Int64)
    @ Base ./array.jl:840
  [2] _unsafe_copyto!(dest::Vector{Pkg.Types.PackageSpec}, doffs::Int64, src::Vector{Pkg.Types.PackageSpec}, soffs::Int64, n::Int64)
    @ Base ./array.jl:235
  [3] unsafe_copyto!
    @ ./array.jl:289 [inlined]
  [4] _copyto_impl!
    @ ./array.jl:313 [inlined]
  [5] copyto!
    @ ./array.jl:299 [inlined]
  [6] append!(a::Vector{Pkg.Types.PackageSpec}, items::Vector{Pkg.Types.PackageSpec})
    @ Base ./array.jl:978
  [7] recall_precompile_state()
    @ Pkg.API ~/Documents/GitHub/Pkg.jl/src/API.jl:1271
  [8] precompile(ctx::Pkg.Types.Context; internal_call::Bool, strict::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API ~/Documents/GitHub/Pkg.jl/src/API.jl:933
  [9] precompile
    @ ~/Documents/GitHub/Pkg.jl/src/API.jl:920 [inlined]
 [10] #precompile#214
    @ ~/Documents/GitHub/Pkg.jl/src/API.jl:918 [inlined]
 [11] precompile()
    @ Pkg.API ~/Documents/GitHub/Pkg.jl/src/API.jl:918
 [12] do_cmd!(command::Pkg.REPLMode.Command, repl::REPL.LineEditREPL)
    @ Pkg.REPLMode ~/Documents/GitHub/Pkg.jl/src/REPLMode/REPLMode.jl:405
 [13] do_cmd(repl::REPL.LineEditREPL, input::String; do_rethrow::Bool)
    @ Pkg.REPLMode ~/Documents/GitHub/Pkg.jl/src/REPLMode/REPLMode.jl:386
 [14] do_cmd
    @ ~/Documents/GitHub/Pkg.jl/src/REPLMode/REPLMode.jl:377 [inlined]
 [15] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
    @ Pkg.REPLMode ~/Documents/GitHub/Pkg.jl/src/REPLMode/REPLMode.jl:550
 [16] #invokelatest#2
    @ ./essentials.jl:734 [inlined]
 [17] invokelatest
    @ ./essentials.jl:732 [inlined]
 [18] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/Documents/GitHub/julia/usr/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:2441
 [19] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/Documents/GitHub/julia/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:1126
 [20] (::REPL.var"#44#49"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ./task.jl:406
```

I tried to come up with a MWE but this didn't error

1.5.3
```
import Pkg, Serialization
open("hello.dat", "w") do io
       serialize(io, Pkg.Types.PackageSpec[])
end
```

1.7
```
import Pkg, Serialization
deserialize("hello.dat")
Pkg.Types.PackageSpec === eltype(deserialize("hello.dat")) # returns true
```

The right thing to do seems to make the cache recall safer, so I'll backport https://github.com/JuliaLang/Pkg.jl/pull/2426 to here

**Comment by DilumAluthge** [comment]
@fredrikekre Is this good to go?

**Comment by DilumAluthge** [comment]
I think probably these will all have to wait until 1.6.1, right?

**Comment by IanButterworth** [comment]
Yeah, I thought that was the case anyway

> On the off-chance these get snuck into 1.6.0

**Comment by DilumAluthge** [comment]
Want to rename this to "1.6.1 backports" and add #2377?

**Comment by IanButterworth** [comment]
Would you mind taking over? I don't have bandwidth currently

**Comment by DilumAluthge** [comment]
I actually have no idea how to backport a PR... maybe @fredrikekre or @KristofferC can take over this PR.

**Comment by IanButterworth** [comment]
@KristofferC would standard practice to be to switch CI on this branch to 1.6 rather than nightly?

**Comment by IanButterworth** [comment]
@KristofferC now that I know about your backport script, I'm wondering if we should merge this (once tests pass) and start a new tidier one with your script?

Also, if we want to backport https://github.com/JuliaLang/Pkg.jl/pull/2484 that will need https://github.com/JuliaLang/julia/pull/40345 to be on the 1.6 base branch before tests pass.

**Comment by DilumAluthge** [comment]
@KristofferC Did https://github.com/JuliaLang/Pkg.jl/pull/2377 make it into this? I don't see it in the diff.

**Comment by KristofferC** [comment]
Sorry, I made a comment about it but I seem to have not submitted it.

What I wrote was basically that I removed it from backport because:

- The Pkg Servers registry seems to be much better now.
- For 1.7 we want to use https://github.com/JuliaLang/Pkg.jl/pull/2431 which will use Pkg server so it is preferable to test that as much as possible.

**Pull request merged**
