### PR TITLE
Make build errors fatal

### PR DESCRIPTION
**Pull request by simonbyrne**
Sort of addresses #1411.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Where would be a good place to add tests?

**Comment by KristofferC** [comment]
Imo this should just be unconditionally true (like in pre 1.0)

**Comment by ExpandingMan** [comment]
I'm not so sure... I'm in the middle of a situation right now where I have one package where the build failing is unavoidable, and the only way to possibly fix it is to try to do this in the build step of the package that's being installed.  This is of course *not* my preference of how to deal with this, but if this were always fatal, I think I'd really be up a creek.

**Comment by KristofferC** [comment]
Use a try catch then? Like in all other cases with exceptions.

**Comment by DilumAluthge** [comment]
> Imo this should just be unconditionally true (like in pre 1.0)

If this happens, I think it has the potential to break packages that currently assume that build failures are not fatal.

If we want to make this the default behavior, I think that we should first do a full PkgEval run to see how many packages it would break.

**Comment by ExpandingMan** [comment]
How can I use try/catch if the thing I need to catch is in another packages build step?

The point is, if a packages build is breaking, and this fatally broke the build of everything else, it would be very hard to resolve it without forking the package that's breaking.

I don't have any specific suggestions here, obviously trying to hack a broken build after the fact is horrible anyway, I'm just pointing out a situation I'm encountering.

**Comment by simonbyrne** [comment]
> I'm not so sure... I'm in the middle of a situation right now where I have one package where the build failing is unavoidable, and the only way to possibly fix it is to try to do this in the build step of the package that's being installed

Can you expand on how this happens?

**Comment by ExpandingMan** [comment]
It's a situation with [Gurobi](https://github.com/JuliaOpt/Gurobi.jl) which has generally been a pain in the ass with these sort of things (referring to Gurobi itself, not the Julia wrapper).  I've wound up needing to let Gurobi.jl try to build itself, but if it fails I fetch Gurobi binaries and explicitly call `Pkg.build("Gurobi")` explicitly in my build step.

I suppose I should probably just make a PR to Gurobi.jl to make this unnecessary (which I will when I get a chance), but there seems to be a general point that if we make a build step failing be *necessarily* fatal, there may be circumstances in which it's almost impossible to circumvent.

That said, I'm *NOT* advocating that users should be encouraged to go through these sorts of awful hacks, it's definitely not ideal.  I think what we need is a clever, well-thought-out solution, but I'm afraid I can't offer any at the moment.

**Comment by simonbyrne** [comment]
That's a good point: we do need a good pattern to allow for optional failures, especially when the dependencies can't be provided as artifacts.

**Comment by KristofferC** [comment]
> If this happens, I think it has the potential to break packages that currently assume that build failures are not fatal.

What does this even mean? This is talking about when packages are getting installed, before any code is running.

**Comment by ExpandingMan** [comment]
> What does this even mean? This is talking about when packages are getting installed / built, before any code is running.

I think the concern is about a failed build step from one package breaking the build steps of all other packages.  Now that I think more about it, maybe it's not so bad that these are completely independent, there just needs to be more transparency about what happened in all the build steps.

Maybe we all have different notions of what "fatal" means here?

**Comment by KristofferC** [comment]
> I think the concern is about a failed build step from one package breaking the build steps of all other packages. 

That is not what happens. After all build steps are done, an exception is thrown if one of the packages failed to build.

**Comment by KristofferC** [comment]
Or that is what is supposed to happen.. I haven't looked at the actual PR yet heh

**Comment by StefanKarpinski** [comment]
Seems like there's an unresolved question here; @KristofferC has proposed that rather than threading yet another option through all the functions, that we should just make build failures unconditionally be errors, which a lot of people (myself included) feel is the way to go. The way to do it seems like it is to try to build everything, remember which ones didn't work and then raise a single large error at the end of the build phase indicating which builds failed with instructions on how to debug, e.g. how to dev those packages and manually try to build them.

**Comment by simonbyrne** [comment]
Any reason why you wouldn't want to just bail on the first failure? You could end up in a case where 1 package build failure (e.g. Conda.jl) prevents all downstream packages from building (if their build steps depend on Conda.jl).

**Comment by StefanKarpinski** [comment]
That seems fine to me as well.

**Comment by simonbyrne** [comment]
Okay, changed to a fatal error.

**Comment by simonbyrne** [comment]
So the problem is that previously this swallowed errors that ZMQ.jl failed to build:
https://travis-ci.org/github/JuliaLang/Pkg.jl/jobs/713035241#L266
and now it doesn't
https://travis-ci.org/github/JuliaLang/Pkg.jl/jobs/714635245#L292

The test that is failing is there to check compatibility with the old REQUIRE format. Unfortunately this is now broken due to the removal of a function from Base, and the older version of Compat.jl doesn't work (https://github.com/JuliaLang/Compat.jl/pull/671).

Any ideas on the best way to fix this?

**Comment by simonbyrne** [comment]
I've removed it for now. The REQUIRE format is still being tested by Permutations.jl

**Comment by simonbyrne** [comment]
bump?

**Comment by StefanKarpinski** [comment]
Just to clarify, this now makes build failures strictly fatal, right? If so, I'm fine with it.

**Comment by simonbyrne** [comment]
> Just to clarify, this now makes build failures strictly fatal, right? If so, I'm fine with it.

Yes

**Pull request merged**
