### PR TITLE
RFC: Add warning for case dependent file distinction fix: #1094

### PR DESCRIPTION
**Pull request by laborg**
Having filenames which only differ by case leads to problems on case 
insensitive OSes.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Seems like this check should be done when installing the package.

**Comment by StefanKarpinski** [comment]
Isn’t it too late when installing? On a system where this is a problem you won’t be able to detect this because the problematic setup is impossible to create. On a system where this isn’t a problem it seems a bit weird to warn/error since it’s not a problem there. It seems more like something to check at registration time, no?

**Comment by StefanKarpinski** [comment]
Doing it at test time is a decent time too.

**Comment by laborg** [comment]
In my case it would have been helpful at test time, but having it (at any time) is better than the error message you get at the moment.

**Comment by 00vareladavid** [comment]
I would prefer to put this in the registration system, because the check is only run once. I'm resistant to crawling the directory tree on every `test`.

**Comment by StefanKarpinski** [comment]
We probably want some reusable way to sanity check a package before trying to register it which can be reused and enforced during registration.

**Comment by 00vareladavid** [comment]
I think `RegistryCI` is a more appropriate location for this code. If so, can we close this and open an issue there?

**Comment by KristofferC** [comment]
Yes, adding this to the registry checks feels like a better idea.

**Pull request closed without merging**
