### PR TITLE
Make tests robust against init.defaultBranch being set

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Review by KristofferC — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@IanButterworth I suspect (but am not 100% sure) that this PR is why the Buildkite Pkg tests are repeatedly failing on https://github.com/JuliaLang/julia/pull/43849.

**Comment by IanButterworth** [comment]
Yeah, seems so https://buildkite.com/julialang/julia-master/builds/7789#417b3551-625f-4d26-b5b1-7b56d208ed04/272-333
```
Pkg             (7) \|         failed at 2022-01-17T19:26:43.241
--
  | Error During Test at /cache/build/dockerized-amdci4-8/julialang/julia-master/julia-ad71912583/share/julia/stdlib/v1.8/Pkg/test/subdir.jl:112
  | Got exception outside of a @test
  | failed process: Process(`git -C /cache/build/dockerized-amdci4-8/julialang/julia-master/tmp/jl_cwdfPO -c user.name=RegistratorTests -c user.email=ci@juliacomputing.com init -b master -q`, ProcessExited(129)) [129]
  |  
  | Stacktrace:
  | [1] pipeline_error
  | @ ./process.jl:542 [inlined]
  | [2] run(::Base.CmdRedirect; wait::Bool)
  | @ Base ./process.jl:457
  | [3] run(::Base.CmdRedirect)
  | @ Base ./process.jl:455
  | [4] setup_packages_repository(dir::String)
  | @ Main.Test90Main_Pkg.PkgTests.SubdirTests /cache/build/dockerized-amdci4-8/julialang/julia-master/julia-ad71912583/share/julia/stdlib/v1.8/Pkg/test/subdir.jl:47
  | [5] (::Main.Test90Main_Pkg.PkgTests.SubdirTests.var"#1#2")(depot::String)
  | @ Main.Test90Main_Pkg.PkgTests.SubdirTests /cache/build/dockerized-amdci4-8/julialang/julia-master/julia-ad71912583/share/julia/stdlib/v1.8/Pkg/test/subdir.jl:124
...
```

**Comment by DilumAluthge** [comment]
@vchuravy What version of Git was the `-b` flag added in?

**Comment by DilumAluthge** [comment]
I suspect we may need to update the version of Git in our rootfs images.

**Comment by IanButterworth** [comment]
Apparently it was added in git 2.28
https://stackoverflow.com/a/64787736/1364192

**Comment by DilumAluthge** [comment]
I can update our rootfs images to use at least Git 2.28.

Note however that this also increases the Git version requirement for any user that wants to run `make testall` locally. Are we comfortable with that increased version requirement?

**Comment by DilumAluthge** [comment]
Alternatively, @vchuravy is there a way you could revert this PR and instead push a change that solves the original problem while also working with older versions of Git?

**Comment by vchuravy** [comment]
I think the only option that comes to mind is to parse the version number... If someone has an old git laying around. What does `git config init.defaultBranch` return?

**Comment by fredrikekre** [comment]
```
$ git config init.defaultBranch

$ git --version
git version 2.25.1
```

**Comment by vchuravy** [comment]
Okay so that's a workable feature test. Let me put up a PR

**Comment by fredrikekre** [comment]
If I actually set it in the config it will return that though
```
$ git config --global init.defaultBranch s

$ git config init.defaultBranch
s
```

**Comment by vchuravy** [comment]
Ah that's bollocks

**Pull request merged**
